/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

/// <reference path="./manifest.d.ts" />
import type { InferData, InferVariants } from '@adonisjs/core/types/transformers'
import type ApiKeyTransformer from '#transformers/api_key_transformer'
import type FlowTransformer from '#transformers/flow_transformer'
import type IntegrationConnectionTransformer from '#transformers/integration_connection_transformer'
import type InvoiceTransformer from '#transformers/invoice_transformer'
import type KnowledgeDocumentTransformer from '#transformers/knowledge_document_transformer'
import type OrganizationSmtpTransformer from '#transformers/organization_smtp_transformer'
import type PlanTransformer from '#transformers/plan_transformer'
import type PlatformFlowCatalogTransformer from '#transformers/platform_flow_catalog_transformer'
import type PlatformTemplateCatalogTransformer from '#transformers/platform_template_catalog_transformer'
import type PlatformUserTransformer from '#transformers/platform_user_transformer'
import type UserTransformer from '#transformers/user_transformer'

export namespace Data {
  export type ApiKey = InferData<ApiKeyTransformer>
  export namespace ApiKey {
    export type Variants = InferVariants<ApiKeyTransformer>
  }
  export type Flow = InferData<FlowTransformer>
  export namespace Flow {
    export type Variants = InferVariants<FlowTransformer>
  }
  export type IntegrationConnection = InferData<IntegrationConnectionTransformer>
  export namespace IntegrationConnection {
    export type Variants = InferVariants<IntegrationConnectionTransformer>
  }
  export type Invoice = InferData<InvoiceTransformer>
  export namespace Invoice {
    export type Variants = InferVariants<InvoiceTransformer>
  }
  export type KnowledgeDocument = InferData<KnowledgeDocumentTransformer>
  export namespace KnowledgeDocument {
    export type Variants = InferVariants<KnowledgeDocumentTransformer>
  }
  export type OrganizationSmtp = InferData<OrganizationSmtpTransformer>
  export namespace OrganizationSmtp {
    export type Variants = InferVariants<OrganizationSmtpTransformer>
  }
  export type Plan = InferData<PlanTransformer>
  export namespace Plan {
    export type Variants = InferVariants<PlanTransformer>
  }
  export type PlatformFlowCatalog = InferData<PlatformFlowCatalogTransformer>
  export namespace PlatformFlowCatalog {
    export type Variants = InferVariants<PlatformFlowCatalogTransformer>
  }
  export type PlatformTemplateCatalog = InferData<PlatformTemplateCatalogTransformer>
  export namespace PlatformTemplateCatalog {
    export type Variants = InferVariants<PlatformTemplateCatalogTransformer>
  }
  export type PlatformUser = InferData<PlatformUserTransformer>
  export namespace PlatformUser {
    export type Variants = InferVariants<PlatformUserTransformer>
  }
  export type User = InferData<UserTransformer>
  export namespace User {
    export type Variants = InferVariants<UserTransformer>
  }
}
