packages:
  - 'apps/*'

allowBuilds:
  '@parcel/watcher': false
  '@swc/core': true
  better-sqlite3: true
  esbuild: true
  msgpackr-extract: true
  sharp: false
  unrs-resolver: false
onlyBuiltDependencies:
  - better-sqlite3
