import { FIXTURE_IDS } from '#database/demo/fixture_ids'
import { jsonb, upsertById } from '#database/demo/helpers'
import type { DemoSeedModule } from '#database/demo/types'

const GROWTH_FEATURES = [
  { key: 'wabaConnection', name: 'Connect Meta & WABA', enabled: true, category: 'integrations' },
  {
    key: 'contactCsvImportExport',
    name: 'CSV Import/Export',
    enabled: true,
    category: 'messaging',
  },
  { key: 'customTemplates', name: 'Custom Templates', enabled: true, category: 'messaging' },
  { key: 'scheduledCampaigns', name: 'Scheduled Campaigns', enabled: true, category: 'automation' },
  { key: 'flowBuilder', name: 'Flow Builder', enabled: true, category: 'automation' },
  { key: 'flowAdvancedNodes', name: 'Advanced Flow Nodes', enabled: true, category: 'automation' },
  { key: 'aiAutonomous', name: 'AI Autonomous', enabled: true, category: 'ai' },
  {
    key: 'eCommerceIntegrations',
    name: 'E-Commerce Integrations',
    enabled: true,
    category: 'integrations',
  },
  { key: 'apiAccess', name: 'API Access', enabled: true, category: 'integrations' },
  { key: 'customRoles', name: 'Custom Roles', enabled: true, category: 'team' },
]

export const plansModule: DemoSeedModule = {
  id: 'plans',
  ownedTables: ['plans'],
  dependsOn: [],
  async seed(ctx) {
    const rows = [
      {
        id: FIXTURE_IDS.plans.starter,
        code: 'starter',
        name: 'Starter',
        description: 'Free tier for small teams',
        price: 0,
        currency: 'INR',
        billingInterval: 'month',
        billingIntervalCount: 1,
        trialDays: 0,
        gateway: null as string | null,
        gatewayPlanId: null as string | null,
        isActive: false,
        sortOrder: 10,
        limits: jsonb({
          users: 3,
          seats: 3,
          whatsappNumbers: 1,
          maxContacts: 1000,
          messagesPerMonth: 500,
          campaignsPerMonth: 10,
          maxBroadcastRecipients: 1000,
          storageBytes: 1_073_741_824,
          maxFileUploadMb: 10,
          maxActiveFlows: 2,
          maxKnowledgeDocs: 3,
          maxKnowledgeDocSizeMb: 5,
          aiRepliesPerMonth: 100,
          maxStoreConnections: 1,
          maxApiKeys: 0,
          maxWebhookEndpoints: 0,
          analyticsRetentionDays: 14,
          auditLogRetentionDays: 7,
          maxTemplates: 25,
          maxCampaignRecipientListSize: 1000,
          conversationInboxRetentionDays: 90,
          aiGenerationsPerConversationHour: 10,
          dispatchRatePerSec: 10,
        }),
        metadata: jsonb({ status: 'archived', features: [] }),
      },
      {
        id: FIXTURE_IDS.plans.growth,
        code: 'growth',
        name: 'Growth',
        description: 'For growing support teams',
        price: 2499,
        currency: 'INR',
        billingInterval: 'month',
        billingIntervalCount: 1,
        trialDays: 0,
        gateway: null as string | null,
        gatewayPlanId: null as string | null,
        isActive: true,
        sortOrder: 20,
        limits: jsonb({
          users: 15,
          seats: 15,
          whatsappNumbers: 3,
          maxContacts: 10_000,
          messagesPerMonth: 10_000,
          campaignsPerMonth: null,
          maxBroadcastRecipients: 10_000,
          storageBytes: 10_737_418_240,
          maxFileUploadMb: 25,
          maxActiveFlows: 15,
          maxKnowledgeDocs: 25,
          maxKnowledgeDocSizeMb: 20,
          aiRepliesPerMonth: 1000,
          maxStoreConnections: 3,
          maxApiKeys: 3,
          maxWebhookEndpoints: 5,
          analyticsRetentionDays: 90,
          auditLogRetentionDays: 90,
          maxTemplates: 100,
          maxCampaignRecipientListSize: 10_000,
          conversationInboxRetentionDays: 365,
          aiGenerationsPerConversationHour: 20,
          dispatchRatePerSec: 20,
        }),
        metadata: jsonb({
          status: 'active',
          popular: true,
          features: GROWTH_FEATURES,
        }),
      },
      {
        id: FIXTURE_IDS.plans.scale,
        code: 'scale',
        name: 'Scale',
        description: 'High-volume organizations',
        price: 7499,
        currency: 'INR',
        billingInterval: 'month',
        billingIntervalCount: 1,
        trialDays: 0,
        gateway: null as string | null,
        gatewayPlanId: null as string | null,
        isActive: true,
        sortOrder: 30,
        limits: jsonb({
          users: 50,
          seats: 50,
          whatsappNumbers: 10,
          maxContacts: null,
          messagesPerMonth: 100_000,
          campaignsPerMonth: null,
          maxBroadcastRecipients: null,
          storageBytes: 107_374_182_400,
          maxFileUploadMb: 64,
          maxActiveFlows: null,
          maxKnowledgeDocs: null,
          maxKnowledgeDocSizeMb: 100,
          aiRepliesPerMonth: null,
          maxStoreConnections: null,
          maxApiKeys: 25,
          maxWebhookEndpoints: null,
          analyticsRetentionDays: null,
          auditLogRetentionDays: 365,
          maxTemplates: 500,
          maxCampaignRecipientListSize: 50_000,
          conversationInboxRetentionDays: 730,
          aiGenerationsPerConversationHour: 60,
          dispatchRatePerSec: 40,
        }),
        metadata: jsonb({
          status: 'active',
          features: GROWTH_FEATURES,
        }),
      },
    ]

    for (const row of rows) {
      await upsertById('plans', row.id, {
        code: row.code,
        name: row.name,
        description: row.description,
        price: row.price,
        currency: row.currency,
        billingInterval: row.billingInterval,
        billingIntervalCount: row.billingIntervalCount,
        trialDays: row.trialDays,
        gateway: row.gateway,
        gatewayPlanId: row.gatewayPlanId,
        isActive: row.isActive,
        sortOrder: row.sortOrder,
        limits: row.limits,
        metadata: row.metadata,
      })
    }

    ctx.plans = { ...FIXTURE_IDS.plans }
  },
}
