import { PERMISSIONS, type Permission } from './permissions.ts'

/**
 * Default permission templates for global system roles (admin/agent/viewer).
 * Seeded into `role_permissions` by rbac_seeder. Tenants customize via
 * `organization_role_permissions` overrides (admin/agent/viewer) or by creating
 * org-scoped custom roles that own their own `role_permissions` rows.
 *
 * Intentionally withheld from Admin template (owner-only until product says otherwise):
 * - billing:manage
 * - whatsapp:connect
 * - org:settings_manage / org:delete
 */
export const SEEDED_ROLES: Array<{ role: string; permissions: Permission[] }> = [
  {
    role: 'admin',
    permissions: [
      PERMISSIONS.INBOX_VIEW,
      PERMISSIONS.INBOX_REPLY,
      PERMISSIONS.INBOX_ASSIGN,
      PERMISSIONS.INBOX_CLOSE,
      PERMISSIONS.HISTORY_EXPORT,
      PERMISSIONS.CONTACTS_VIEW,
      PERMISSIONS.CONTACTS_CREATE,
      PERMISSIONS.CONTACTS_EDIT,
      PERMISSIONS.CONTACTS_DELETE,
      PERMISSIONS.CONTACTS_IMPORT,
      PERMISSIONS.CONTACTS_EXPORT,
      PERMISSIONS.TEMPLATES_VIEW,
      PERMISSIONS.TEMPLATES_CREATE,
      PERMISSIONS.TEMPLATES_EDIT,
      PERMISSIONS.TEMPLATES_DELETE,
      PERMISSIONS.TEMPLATES_SYNC,
      PERMISSIONS.CAMPAIGNS_VIEW,
      PERMISSIONS.CAMPAIGNS_CREATE,
      PERMISSIONS.CAMPAIGNS_EDIT,
      PERMISSIONS.CAMPAIGNS_PAUSE,
      PERMISSIONS.CAMPAIGNS_LAUNCH,
      PERMISSIONS.CAMPAIGNS_DELETE,
      PERMISSIONS.AUTOMATIONS_VIEW,
      PERMISSIONS.AUTOMATIONS_CREATE,
      PERMISSIONS.AUTOMATIONS_EDIT,
      PERMISSIONS.AUTOMATIONS_DELETE,
      PERMISSIONS.AUTOMATIONS_TOGGLE,
      PERMISSIONS.AI_DRAFT,
      PERMISSIONS.AI_KB_VIEW,
      PERMISSIONS.AI_KB_MANAGE,
      PERMISSIONS.AI_AGENT_MANAGE,
      PERMISSIONS.NOTIFICATIONS_MANAGE,
      PERMISSIONS.ANALYTICS_VIEW,
      PERMISSIONS.ANALYTICS_EXPORT,
      PERMISSIONS.ORG_VIEW,
      PERMISSIONS.TEAM_VIEW,
      PERMISSIONS.TEAM_INVITE,
      PERMISSIONS.TEAM_REMOVE,
      PERMISSIONS.TEAM_ROLE_ASSIGN,
      PERMISSIONS.ROLES_VIEW,
      PERMISSIONS.ROLES_MANAGE,
      PERMISSIONS.BILLING_VIEW,
      PERMISSIONS.WHATSAPP_VIEW,
      PERMISSIONS.INTEGRATIONS_VIEW,
      PERMISSIONS.INTEGRATIONS_MANAGE,
      PERMISSIONS.AUDIT_LOG_VIEW,
    ],
  },
  {
    role: 'agent',
    permissions: [
      PERMISSIONS.INBOX_VIEW,
      PERMISSIONS.INBOX_REPLY,
      PERMISSIONS.INBOX_ASSIGN,
      PERMISSIONS.INBOX_CLOSE,
      PERMISSIONS.CONTACTS_VIEW,
      PERMISSIONS.TEMPLATES_VIEW,
      PERMISSIONS.CAMPAIGNS_VIEW,
      PERMISSIONS.AUTOMATIONS_VIEW,
      PERMISSIONS.AI_DRAFT,
      PERMISSIONS.AI_KB_VIEW,
      PERMISSIONS.ORG_VIEW,
      PERMISSIONS.TEAM_VIEW,
    ],
  },
  {
    role: 'viewer',
    permissions: [
      PERMISSIONS.INBOX_VIEW,
      PERMISSIONS.CONTACTS_VIEW,
      PERMISSIONS.TEMPLATES_VIEW,
      PERMISSIONS.CAMPAIGNS_VIEW,
      PERMISSIONS.AUTOMATIONS_VIEW,
      PERMISSIONS.AI_KB_VIEW,
      PERMISSIONS.ANALYTICS_VIEW,
      PERMISSIONS.ORG_VIEW,
    ],
  },
]
