/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class AccountSchema extends BaseModel {
  static $columns = ['accessToken', 'accessTokenExpiresAt', 'accountId', 'createdAt', 'id', 'idToken', 'password', 'providerId', 'refreshToken', 'refreshTokenExpiresAt', 'scope', 'updatedAt', 'userId'] as const
  $columns = AccountSchema.$columns
  @column()
  declare accessToken: string | null
  @column.dateTime()
  declare accessTokenExpiresAt: DateTime | null
  @column()
  declare accountId: string
  @column.dateTime()
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare idToken: string | null
  @column({ serializeAs: null })
  declare password: string | null
  @column()
  declare providerId: string
  @column()
  declare refreshToken: string | null
  @column.dateTime()
  declare refreshTokenExpiresAt: DateTime | null
  @column()
  declare scope: string | null
  @column.dateTime()
  declare updatedAt: DateTime | null
  @column()
  declare userId: string
}

export class AuthorizationAuditSchema extends BaseModel {
  static $columns = ['actorUserId', 'after', 'before', 'createdAt', 'eventType', 'granted', 'id', 'organizationId', 'permissionId', 'reason', 'roleId', 'targetId', 'targetType'] as const
  $columns = AuthorizationAuditSchema.$columns
  @column()
  declare actorUserId: string | null
  @column()
  declare after: any | null
  @column()
  declare before: any | null
  @column.dateTime()
  declare createdAt: DateTime
  @column()
  declare eventType: string
  @column()
  declare granted: boolean | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare organizationId: string
  @column()
  declare permissionId: string | null
  @column()
  declare reason: string | null
  @column()
  declare roleId: string | null
  @column()
  declare targetId: string | null
  @column()
  declare targetType: string
}

export class ContactSchema extends BaseModel {
  static $columns = ['company', 'createdAt', 'createdByUserId', 'customFields', 'deletedAt', 'email', 'id', 'name', 'organizationId', 'phone', 'phoneNormalized', 'updatedAt'] as const
  $columns = ContactSchema.$columns
  @column()
  declare company: string | null
  @column.dateTime()
  declare createdAt: DateTime
  @column()
  declare createdByUserId: string | null
  @column()
  declare customFields: any
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column()
  declare email: string | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare name: string | null
  @column()
  declare organizationId: string
  @column()
  declare phone: string
  @column()
  declare phoneNormalized: string
  @column.dateTime()
  declare updatedAt: DateTime | null
}

export class ConversationAssignmentSchema extends BaseModel {
  static $columns = ['agentUserId', 'assignedByUserId', 'conversationId', 'createdAt', 'id', 'organizationId', 'reason'] as const
  $columns = ConversationAssignmentSchema.$columns
  @column()
  declare agentUserId: string | null
  @column()
  declare assignedByUserId: string | null
  @column()
  declare conversationId: string
  @column.dateTime()
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare organizationId: string
  @column()
  declare reason: string | null
}

export class ConversationNoteSchema extends BaseModel {
  static $columns = ['authorUserId', 'body', 'conversationId', 'createdAt', 'id', 'organizationId', 'updatedAt'] as const
  $columns = ConversationNoteSchema.$columns
  @column()
  declare authorUserId: string
  @column()
  declare body: string
  @column()
  declare conversationId: string
  @column.dateTime()
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare organizationId: string
  @column.dateTime()
  declare updatedAt: DateTime | null
}

export class ConversationSchema extends BaseModel {
  static $columns = ['assignedAgentId', 'closedAt', 'contactId', 'createdAt', 'firstResponseAt', 'id', 'lastMessageAt', 'lastMessageText', 'organizationId', 'status', 'unreadCount', 'updatedAt', 'whatsappConfigId'] as const
  $columns = ConversationSchema.$columns
  @column()
  declare assignedAgentId: string | null
  @column.dateTime()
  declare closedAt: DateTime | null
  @column()
  declare contactId: string
  @column.dateTime()
  declare createdAt: DateTime
  @column.dateTime()
  declare firstResponseAt: DateTime | null
  @column({ isPrimary: true })
  declare id: string
  @column.dateTime()
  declare lastMessageAt: DateTime | null
  @column()
  declare lastMessageText: string | null
  @column()
  declare organizationId: string
  @column()
  declare status: string
  @column()
  declare unreadCount: number
  @column.dateTime()
  declare updatedAt: DateTime | null
  @column()
  declare whatsappConfigId: string
}

export class JwkSchema extends BaseModel {
  static $columns = ['alg', 'createdAt', 'crv', 'expiresAt', 'id', 'privateKey', 'publicKey'] as const
  $columns = JwkSchema.$columns
  @column()
  declare alg: string | null
  @column.dateTime()
  declare createdAt: DateTime
  @column()
  declare crv: string | null
  @column.dateTime()
  declare expiresAt: DateTime | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare privateKey: string
  @column()
  declare publicKey: string
}

export class MediaAssetSchema extends BaseModel {
  static $columns = ['fileName', 'filePath', 'fileSize', 'id', 'mimeType', 'organizationId', 'uploadedAt', 'uploadedBy'] as const
  $columns = MediaAssetSchema.$columns
  @column()
  declare fileName: string
  @column()
  declare filePath: string
  @column()
  declare fileSize: bigint | number
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare mimeType: string
  @column()
  declare organizationId: string
  @column.dateTime()
  declare uploadedAt: DateTime
  @column()
  declare uploadedBy: string | null
}

export class MessageTemplateSchema extends BaseModel {
  static $columns = ['bodyText', 'buttons', 'category', 'createdAt', 'createdByUserId', 'footerText', 'headerContent', 'headerMediaUrl', 'headerType', 'id', 'language', 'lastSubmittedAt', 'metaTemplateId', 'name', 'organizationId', 'parameterSchema', 'qualityScore', 'rejectionReason', 'sampleValues', 'status', 'submissionError', 'updatedAt', 'whatsappConfigId'] as const
  $columns = MessageTemplateSchema.$columns
  @column()
  declare bodyText: string
  @column()
  declare buttons: any | null
  @column()
  declare category: string
  @column.dateTime()
  declare createdAt: DateTime
  @column()
  declare createdByUserId: string | null
  @column()
  declare footerText: string | null
  @column()
  declare headerContent: string | null
  @column()
  declare headerMediaUrl: string | null
  @column()
  declare headerType: string | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare language: string | null
  @column.dateTime()
  declare lastSubmittedAt: DateTime | null
  @column()
  declare metaTemplateId: string | null
  @column()
  declare name: string
  @column()
  declare organizationId: string
  @column()
  declare parameterSchema: any
  @column()
  declare qualityScore: string | null
  @column()
  declare rejectionReason: string | null
  @column()
  declare sampleValues: any | null
  @column()
  declare status: string
  @column()
  declare submissionError: string | null
  @column.dateTime()
  declare updatedAt: DateTime | null
  @column()
  declare whatsappConfigId: string | null
}

export class MessageSchema extends BaseModel {
  static $columns = ['contentText', 'contentType', 'conversationId', 'createdAt', 'deliveredAt', 'errorMessage', 'failedAt', 'id', 'interactivePayload', 'interactiveReplyId', 'mediaAssetId', 'mediaUrl', 'messageTemplateId', 'metadata', 'occurredAt', 'organizationId', 'providerMessageId', 'providerStatusAt', 'readAt', 'replyToMessageId', 'senderId', 'senderType', 'sentAt', 'status', 'updatedAt'] as const
  $columns = MessageSchema.$columns
  @column()
  declare contentText: string | null
  @column()
  declare contentType: string
  @column()
  declare conversationId: string
  @column.dateTime()
  declare createdAt: DateTime
  @column.dateTime()
  declare deliveredAt: DateTime | null
  @column()
  declare errorMessage: string | null
  @column.dateTime()
  declare failedAt: DateTime | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare interactivePayload: any | null
  @column()
  declare interactiveReplyId: string | null
  @column()
  declare mediaAssetId: string | null
  @column()
  declare mediaUrl: string | null
  @column()
  declare messageTemplateId: string | null
  @column()
  declare metadata: any
  @column.dateTime()
  declare occurredAt: DateTime | null
  @column()
  declare organizationId: string
  @column()
  declare providerMessageId: string | null
  @column.dateTime()
  declare providerStatusAt: DateTime | null
  @column.dateTime()
  declare readAt: DateTime | null
  @column()
  declare replyToMessageId: string | null
  @column()
  declare senderId: string | null
  @column()
  declare senderType: string
  @column.dateTime()
  declare sentAt: DateTime | null
  @column()
  declare status: string
  @column.dateTime()
  declare updatedAt: DateTime | null
}

export class OrganizationInvitationSchema extends BaseModel {
  static $columns = ['createdAt', 'email', 'expiresAt', 'id', 'inviterId', 'organizationId', 'roleId', 'status'] as const
  $columns = OrganizationInvitationSchema.$columns
  @column.dateTime()
  declare createdAt: DateTime
  @column()
  declare email: string
  @column.dateTime()
  declare expiresAt: DateTime
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare inviterId: string
  @column()
  declare organizationId: string
  @column()
  declare roleId: string
  @column()
  declare status: string
}

export class OrganizationMemberSchema extends BaseModel {
  static $columns = ['createdAt', 'deletedAt', 'id', 'isDeleted', 'organizationId', 'permissionVersion', 'roleId', 'userId'] as const
  $columns = OrganizationMemberSchema.$columns
  @column.dateTime()
  declare createdAt: DateTime
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare isDeleted: boolean
  @column()
  declare organizationId: string
  @column()
  declare permissionVersion: number
  @column()
  declare roleId: string
  @column()
  declare userId: string
}

export class OrganizationRolePermissionSchema extends BaseModel {
  static $columns = ['granted', 'id', 'organizationId', 'permissionId', 'roleId'] as const
  $columns = OrganizationRolePermissionSchema.$columns
  @column()
  declare granted: boolean
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare organizationId: string
  @column()
  declare permissionId: string
  @column()
  declare roleId: string
}

export class OrganizationSubscriptionSchema extends BaseModel {
  static $columns = ['cancelAt', 'createdAt', 'currentPeriodEnd', 'currentPeriodStart', 'id', 'organizationId', 'planId', 'status', 'updatedAt'] as const
  $columns = OrganizationSubscriptionSchema.$columns
  @column.dateTime()
  declare cancelAt: DateTime | null
  @column.dateTime()
  declare createdAt: DateTime
  @column.dateTime()
  declare currentPeriodEnd: DateTime
  @column.dateTime()
  declare currentPeriodStart: DateTime
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare organizationId: string
  @column()
  declare planId: string
  @column()
  declare status: string
  @column.dateTime()
  declare updatedAt: DateTime | null
}

export class OrganizationSchema extends BaseModel {
  static $columns = ['country', 'createdAt', 'currency', 'deletedAt', 'email', 'id', 'industry', 'name', 'phone', 'slug', 'status', 'timezone', 'updatedAt', 'website'] as const
  $columns = OrganizationSchema.$columns
  @column()
  declare country: string
  @column.dateTime()
  declare createdAt: DateTime
  @column()
  declare currency: string | null
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column()
  declare email: string
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare industry: string | null
  @column()
  declare name: string
  @column()
  declare phone: string | null
  @column()
  declare slug: string
  @column()
  declare status: boolean
  @column()
  declare timezone: string
  @column.dateTime()
  declare updatedAt: DateTime | null
  @column()
  declare website: string | null
}

export class OutboundDispatchSchema extends BaseModel {
  static $columns = ['attempts', 'completedAt', 'createdAt', 'errorCode', 'errorMessage', 'id', 'lockedAt', 'lockExpiresAt', 'lockOwner', 'messageId', 'nextAttemptAt', 'organizationId', 'payload', 'status', 'updatedAt', 'whatsappConfigId'] as const
  $columns = OutboundDispatchSchema.$columns
  @column()
  declare attempts: number
  @column.dateTime()
  declare completedAt: DateTime | null
  @column.dateTime()
  declare createdAt: DateTime
  @column()
  declare errorCode: string | null
  @column()
  declare errorMessage: string | null
  @column({ isPrimary: true })
  declare id: string
  @column.dateTime()
  declare lockedAt: DateTime | null
  @column.dateTime()
  declare lockExpiresAt: DateTime | null
  @column()
  declare lockOwner: string | null
  @column()
  declare messageId: string
  @column.dateTime()
  declare nextAttemptAt: DateTime | null
  @column()
  declare organizationId: string
  @column()
  declare payload: any
  @column()
  declare status: string
  @column.dateTime()
  declare updatedAt: DateTime | null
  @column()
  declare whatsappConfigId: string
}

export class PaymentTransactionSchema extends BaseModel {
  static $columns = ['amount', 'createdAt', 'currency', 'gateway', 'gatewayTransactionId', 'id', 'invoiceUrl', 'metadata', 'organizationId', 'status', 'subscriptionId'] as const
  $columns = PaymentTransactionSchema.$columns
  @column()
  declare amount: string
  @column.dateTime()
  declare createdAt: DateTime
  @column()
  declare currency: string
  @column()
  declare gateway: string
  @column()
  declare gatewayTransactionId: string
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare invoiceUrl: string | null
  @column()
  declare metadata: any
  @column()
  declare organizationId: string
  @column()
  declare status: string
  @column()
  declare subscriptionId: string
}

export class PermissionSchema extends BaseModel {
  static $columns = ['action', 'createdAt', 'description', 'id', 'module', 'name'] as const
  $columns = PermissionSchema.$columns
  @column()
  declare action: string
  @column.dateTime()
  declare createdAt: DateTime
  @column()
  declare description: string | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare module: string
  @column()
  declare name: string
}

export class PlanSchema extends BaseModel {
  static $columns = ['billingInterval', 'createdAt', 'currency', 'id', 'limits', 'name', 'price', 'updatedAt'] as const
  $columns = PlanSchema.$columns
  @column()
  declare billingInterval: string
  @column.dateTime()
  declare createdAt: DateTime
  @column()
  declare currency: string
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare limits: any
  @column()
  declare name: string
  @column()
  declare price: string
  @column.dateTime()
  declare updatedAt: DateTime | null
}

export class RolePermissionSchema extends BaseModel {
  static $columns = ['permissionId', 'roleId'] as const
  $columns = RolePermissionSchema.$columns
  @column()
  declare permissionId: string
  @column()
  declare roleId: string
}

export class RoleSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'name', 'organizationId', 'updatedAt'] as const
  $columns = RoleSchema.$columns
  @column.dateTime()
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare name: string
  @column()
  declare organizationId: string | null
  @column.dateTime()
  declare updatedAt: DateTime | null
}

export class SessionSchema extends BaseModel {
  static $columns = ['activeOrganizationId', 'createdAt', 'expiresAt', 'id', 'ipAddress', 'token', 'updatedAt', 'userAgent', 'userId'] as const
  $columns = SessionSchema.$columns
  @column()
  declare activeOrganizationId: string | null
  @column.dateTime()
  declare createdAt: DateTime
  @column.dateTime()
  declare expiresAt: DateTime | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare ipAddress: string | null
  @column()
  declare token: string
  @column.dateTime()
  declare updatedAt: DateTime | null
  @column()
  declare userAgent: string | null
  @column()
  declare userId: string
}

export class UnmatchedProviderReceiptSchema extends BaseModel {
  static $columns = ['createdAt', 'errorMessage', 'expiresAt', 'id', 'metadata', 'organizationId', 'providerMessageId', 'providerStatusAt', 'receivedAt', 'status', 'updatedAt', 'whatsappConfigId'] as const
  $columns = UnmatchedProviderReceiptSchema.$columns
  @column.dateTime()
  declare createdAt: DateTime
  @column()
  declare errorMessage: string | null
  @column.dateTime()
  declare expiresAt: DateTime
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare metadata: any
  @column()
  declare organizationId: string
  @column()
  declare providerMessageId: string
  @column.dateTime()
  declare providerStatusAt: DateTime
  @column.dateTime()
  declare receivedAt: DateTime
  @column()
  declare status: string
  @column.dateTime()
  declare updatedAt: DateTime | null
  @column()
  declare whatsappConfigId: string
}

export class UsageMeterSchema extends BaseModel {
  static $columns = ['id', 'limitCount', 'metric', 'organizationId', 'periodEnd', 'periodStart', 'updatedAt', 'usedCount'] as const
  $columns = UsageMeterSchema.$columns
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare limitCount: number
  @column()
  declare metric: string
  @column()
  declare organizationId: string
  @column.dateTime()
  declare periodEnd: DateTime
  @column.dateTime()
  declare periodStart: DateTime
  @column.dateTime()
  declare updatedAt: DateTime
  @column()
  declare usedCount: number
}

export class UserRoleSchema extends BaseModel {
  static $columns = ['id', 'organizationId', 'permissionVersion', 'roleId', 'userId'] as const
  $columns = UserRoleSchema.$columns
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare organizationId: string | null
  @column()
  declare permissionVersion: number
  @column()
  declare roleId: string
  @column()
  declare userId: string
}

export class UserSchema extends BaseModel {
  static $columns = ['createdAt', 'deletedAt', 'email', 'emailVerified', 'firstname', 'id', 'image', 'isActive', 'isDeleted', 'lastname', 'name', 'updatedAt', 'updatedBy'] as const
  $columns = UserSchema.$columns
  @column.dateTime()
  declare createdAt: DateTime
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column()
  declare email: string
  @column()
  declare emailVerified: boolean
  @column()
  declare firstname: string
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare image: string | null
  @column()
  declare isActive: boolean
  @column()
  declare isDeleted: boolean
  @column()
  declare lastname: string
  @column()
  declare name: string
  @column.dateTime()
  declare updatedAt: DateTime | null
  @column()
  declare updatedBy: string | null
}

export class VerificationSchema extends BaseModel {
  static $columns = ['createdAt', 'expiresAt', 'id', 'identifier', 'updatedAt', 'value'] as const
  $columns = VerificationSchema.$columns
  @column.dateTime()
  declare createdAt: DateTime
  @column.dateTime()
  declare expiresAt: DateTime
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare identifier: string
  @column.dateTime()
  declare updatedAt: DateTime | null
  @column()
  declare value: string
}

export class WhatsappConfigSchema extends BaseModel {
  static $columns = ['accessToken', 'connectedAt', 'createdAt', 'createdByUserId', 'id', 'organizationId', 'phoneNumberId', 'registeredAt', 'status', 'subscribedAppsAt', 'updatedAt', 'verifyToken', 'wabaId'] as const
  $columns = WhatsappConfigSchema.$columns
  @column()
  declare accessToken: string
  @column.dateTime()
  declare connectedAt: DateTime | null
  @column.dateTime()
  declare createdAt: DateTime
  @column()
  declare createdByUserId: string | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare organizationId: string
  @column()
  declare phoneNumberId: string
  @column.dateTime()
  declare registeredAt: DateTime | null
  @column()
  declare status: string
  @column.dateTime()
  declare subscribedAppsAt: DateTime | null
  @column.dateTime()
  declare updatedAt: DateTime | null
  @column()
  declare verifyToken: string | null
  @column()
  declare wabaId: string | null
}
