import {
  EMPTY_PLATFORM_BILLING_PROFILE,
  type PlatformBillingProfile,
} from '#lib/platform_billing_profile'
import type { SuperAdminInvoice } from '#types/invoices'

const LINES_PER_PAGE = 48

function pdfEscape(value: string): string {
  let out = ''
  for (const ch of value) {
    const code = ch.charCodeAt(0)
    if (ch === '\\' || ch === '(' || ch === ')') {
      out += `\\${ch}`
      continue
    }
    if (code < 32 || code > 126) {
      out += '?'
      continue
    }
    out += ch
  }
  return out
}

function wrapLine(value: string, width: number): string[] {
  const text = value.replaceAll(/\s+/g, ' ').trim()
  if (!text) return ['']
  const lines: string[] = []
  let remaining = text
  while (remaining.length > width) {
    let breakAt = remaining.lastIndexOf(' ', width)
    if (breakAt < 1) breakAt = width
    lines.push(remaining.slice(0, breakAt).trimEnd())
    remaining = remaining.slice(breakAt).trimStart()
  }
  if (remaining) lines.push(remaining)
  return lines
}

function formatMoney(currency: string, amount: number): string {
  return `${currency} ${amount.toFixed(2)}`
}

function taxPercentLabel(taxRate: number): string {
  const percent = Math.round(taxRate * 10000) / 100
  return Number.isInteger(percent) ? String(percent) : percent.toFixed(2)
}

export function invoicePdfFilename(invoiceNumber: string): string {
  const safe = invoiceNumber.replace(/[^A-Za-z0-9._-]+/g, '-').replace(/^-+|-+$/g, '')
  return `invoice-${safe || 'document'}.pdf`
}

export function buildInvoicePdfLines(
  invoice: SuperAdminInvoice,
  platform: PlatformBillingProfile = EMPTY_PLATFORM_BILLING_PROFILE
): string[] {
  const lines: string[] = [platform.brandName, platform.legalName]
  if (platform.tagline) lines.push(platform.tagline)
  lines.push(...platform.addressLines)
  if (platform.gstin) lines.push(`GSTIN: ${platform.gstin}`)
  const contactParts = [
    platform.email ? `Email: ${platform.email}` : '',
    platform.phone ? `Phone: ${platform.phone}` : '',
  ].filter(Boolean)
  if (contactParts.length > 0) lines.push(contactParts.join('  '))

  lines.push('INVOICE')
  lines.push(`Invoice #: ${invoice.invoiceNumber}`)
  lines.push(`Status: ${invoice.status}`)
  lines.push(`Issue date: ${invoice.issueDate}`)
  lines.push(`Due date: ${invoice.dueDate}`)
  lines.push(`Billing period: ${invoice.billingPeriod}`)
  lines.push(`Plan: ${invoice.planName}`)
  lines.push(`Period: ${invoice.periodStart.slice(0, 10)} to ${invoice.periodEnd.slice(0, 10)}`)
  lines.push('')
  lines.push('Billed to')
  lines.push(invoice.organization.name)
  lines.push(invoice.organization.email)

  if (invoice.organization.phone) lines.push(invoice.organization.phone)
  if (invoice.organization.address) {
    lines.push(...wrapLine(invoice.organization.address, 90))
  }
  if (invoice.organization.gstin) lines.push(`GSTIN: ${invoice.organization.gstin}`)

  lines.push('', 'Line items', 'Description | Qty | Unit price | Amount')
  for (const item of invoice.lineItems) {
    const header = `${item.description} | ${item.quantity} | ${formatMoney(invoice.currency, item.unitPrice)} | ${formatMoney(invoice.currency, item.amount)}`
    lines.push(...wrapLine(header, 90))
    if (item.detail) {
      lines.push(...wrapLine(`  ${item.detail}`, 90))
    }
  }

  lines.push(
    '',
    `Subtotal: ${formatMoney(invoice.currency, invoice.subtotal)}`,
    `Discount: ${formatMoney(invoice.currency, invoice.discount)}`,
    `Tax (${taxPercentLabel(invoice.taxRate)}% GST): ${formatMoney(invoice.currency, invoice.tax)}`,
    `Total: ${formatMoney(invoice.currency, invoice.total)}`
  )

  if (invoice.paymentMethod) lines.push(`Payment method: ${invoice.paymentMethod}`)
  if (invoice.paymentDate) lines.push(`Payment date: ${invoice.paymentDate}`)
  if (invoice.transactionId) lines.push(`Transaction ID: ${invoice.transactionId}`)

  const notes = invoice.notes?.trim()
  if (notes) {
    lines.push('', 'Notes')
    lines.push(...wrapLine(notes, 90))
  }

  if (platform.email) {
    lines.push(
      '',
      `This invoice is generated by ${platform.brandName}. For billing queries, contact ${platform.email}.`
    )
  } else if (platform.website) {
    lines.push('', `This invoice is generated by ${platform.brandName}. ${platform.website}`)
  } else {
    lines.push('', `This invoice is generated by ${platform.brandName}.`)
  }

  return lines
}

function chunkLines(lines: string[], size: number): string[][] {
  if (lines.length === 0) return [[]]
  const pages: string[][] = []
  for (let i = 0; i < lines.length; i += size) {
    pages.push(lines.slice(i, i + size))
  }
  return pages
}

function buildContentStream(lines: string[]): Buffer {
  const commands = ['BT', '/F1 10 Tf', '50 760 Td']
  for (const [index, line] of lines.entries()) {
    if (index > 0) commands.push('0 -14 Td')
    commands.push(`(${pdfEscape(line)}) Tj`)
  }
  commands.push('ET')
  return Buffer.from(commands.join('\n'), 'latin1')
}

function padOffset(offset: number): string {
  return String(offset).padStart(10, '0')
}

/** Minimal PDF 1.4 document for Super Admin invoice download/email attachment. */
export function buildInvoicePdfBuffer(
  invoice: SuperAdminInvoice,
  platform: PlatformBillingProfile = EMPTY_PLATFORM_BILLING_PROFILE
): Buffer {
  const pages = chunkLines(buildInvoicePdfLines(invoice, platform), LINES_PER_PAGE)
  const pageCount = pages.length
  const fontId = 3
  const firstPageId = 4
  const kids = pages.map((_, index) => `${firstPageId + index * 2} 0 R`).join(' ')

  const objects: Buffer[] = []
  const add = (body: string | Buffer) => {
    objects.push(typeof body === 'string' ? Buffer.from(body, 'latin1') : body)
  }

  add('<< /Type /Catalog /Pages 2 0 R >>')
  add(`<< /Type /Pages /Kids [ ${kids} ] /Count ${pageCount} >>`)
  add('<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>')

  for (const [index, pageLines] of pages.entries()) {
    const pageId = firstPageId + index * 2
    const contentId = pageId + 1
    add(
      `<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Contents ${contentId} 0 R /Resources << /Font << /F1 ${fontId} 0 R >> >> >>`
    )
    const stream = buildContentStream(pageLines)
    add(
      Buffer.concat([
        Buffer.from(`<< /Length ${stream.length} >>\nstream\n`, 'latin1'),
        stream,
        Buffer.from('\nendstream', 'latin1'),
      ])
    )
  }

  const header = Buffer.from('%PDF-1.4\n%\xE2\xE3\xCF\xD3\n', 'latin1')
  const parts: Buffer[] = [header]
  const offsets = [0]
  let cursor = header.length

  for (const [index, object] of objects.entries()) {
    const objectId = index + 1
    const objectBytes = Buffer.concat([
      Buffer.from(`${objectId} 0 obj\n`, 'latin1'),
      object,
      Buffer.from('\nendobj\n', 'latin1'),
    ])
    offsets[objectId] = cursor
    parts.push(objectBytes)
    cursor += objectBytes.length
  }

  const xrefStart = cursor
  const size = objects.length + 1
  let xref = `xref\n0 ${size}\n0000000000 65535 f \n`
  for (const offset of offsets.slice(1)) {
    xref += `${padOffset(offset)} 00000 n \n`
  }
  const xrefBuf = Buffer.from(xref, 'latin1')
  parts.push(xrefBuf)
  parts.push(
    Buffer.from(
      `trailer\n<< /Size ${size} /Root 1 0 R >>\nstartxref\n${xrefStart}\n%%EOF\n`,
      'latin1'
    )
  )

  return Buffer.concat(parts)
}
