export enum AiUsageDecision {
  AUTO_REPLIED = 'AUTO_REPLIED',
  HANDOVER_LOW_CONFIDENCE = 'HANDOVER_LOW_CONFIDENCE',
  HANDOVER_KEYWORD = 'HANDOVER_KEYWORD',
  HANDOVER_ERROR = 'HANDOVER_ERROR',
}

export const AI_USAGE_DECISIONS = Object.values(AiUsageDecision)
