export enum FlowNodeType {
  TRIGGER = 'TRIGGER',
  MESSAGE = 'MESSAGE',
  TEMPLATE = 'TEMPLATE',
  INTERACTIVE_BUTTON = 'INTERACTIVE_BUTTON',
  INTERACTIVE_LIST = 'INTERACTIVE_LIST',
  CONDITION = 'CONDITION',
  SUBFLOW = 'SUBFLOW',
  AI_RAG = 'AI_RAG',
  HUMAN_HANDOVER = 'HUMAN_HANDOVER',
  EXIT = 'EXIT',
}

export const FLOW_NODE_TYPES = Object.values(FlowNodeType)
