/**
 * Stand-in for #controllers/* and #validators/* so frontend tsc does not load the backend.
 * Call-site types remain the ones exported from lib/api.ts.
 * Regenerated by scripts/prepare-tuyau-types.mjs.
 *
 * Important: registry schema.d.ts must NOT reference manifest.d.ts or Next/Vercel
 * will typecheck Adonis routes against this stub and fail.
 */
import type { ITYPE } from '@vinejs/vine/build/src/symbols.js'

/* eslint-disable @typescript-eslint/no-explicit-any, @typescript-eslint/no-empty-object-type */
type AnyMethod = (...args: any[]) => any
interface EmptyInput {}
type LooseValidator = { [ITYPE]: EmptyInput }

/** Class default export keeps Adonis Constructor/LazyImport assignable if pulled in. */
export default class TuyauControllerStub {
  [method: string]: AnyMethod
}

export const demoAvailabilityQueryValidator: LooseValidator = {} as LooseValidator
export const createDemoBookingValidator: LooseValidator = {} as LooseValidator
export const genericIntegrationEventValidator: LooseValidator = {} as LooseValidator
export const shopenupIntegrationEventValidator: LooseValidator = {} as LooseValidator
export const completeEmbeddedSignupValidator: LooseValidator = {} as LooseValidator
export const testWhatsappConfigValidator: LooseValidator = {} as LooseValidator
export const listMessageTemplatesValidator: LooseValidator = {} as LooseValidator
export const templateIdParamValidator: LooseValidator = {} as LooseValidator
export const createMessageTemplateValidator: LooseValidator = {} as LooseValidator
export const preSignupValidator: LooseValidator = {} as LooseValidator
export const resendSignupOtpValidator: LooseValidator = {} as LooseValidator
export const verifySignupValidator: LooseValidator = {} as LooseValidator
export const listSuperAdminOrganizationsValidator: LooseValidator = {} as LooseValidator
export const organizationIdParamValidator: LooseValidator = {} as LooseValidator
export const updateOrganizationValidator: LooseValidator = {} as LooseValidator
export const listSuperAdminSubscriptionsValidator: LooseValidator = {} as LooseValidator
export const createSuperAdminSubscriptionValidator: LooseValidator = {} as LooseValidator
export const subscriptionIdParamValidator: LooseValidator = {} as LooseValidator
export const updateSuperAdminSubscriptionValidator: LooseValidator = {} as LooseValidator
export const listSuperAdminPlansValidator: LooseValidator = {} as LooseValidator
export const createSuperAdminPlanValidator: LooseValidator = {} as LooseValidator
export const planIdParamValidator: LooseValidator = {} as LooseValidator
export const updateSuperAdminPlanValidator: LooseValidator = {} as LooseValidator
export const invoiceSummaryValidator: LooseValidator = {} as LooseValidator
export const listSuperAdminInvoicesValidator: LooseValidator = {} as LooseValidator
export const createSuperAdminInvoiceValidator: LooseValidator = {} as LooseValidator
export const invoiceIdParamValidator: LooseValidator = {} as LooseValidator
export const markSuperAdminInvoicePaidValidator: LooseValidator = {} as LooseValidator
export const regenerateSuperAdminInvoiceValidator: LooseValidator = {} as LooseValidator
export const updatePlatformSettingsValidator: LooseValidator = {} as LooseValidator
export const updatePlatformAiConfigValidator: LooseValidator = {} as LooseValidator
export const listPlatformAuditValidator: LooseValidator = {} as LooseValidator
export const listSuperAdminPlatformUsersValidator: LooseValidator = {} as LooseValidator
export const globalSearchQueryValidator: LooseValidator = {} as LooseValidator
export const listOrganizationAdminUsersValidator: LooseValidator = {} as LooseValidator
export const organizationAdminUserIdParamValidator: LooseValidator = {} as LooseValidator
export const updateOrganizationAdminUserValidator: LooseValidator = {} as LooseValidator
export const createOrganizationValidator: LooseValidator = {} as LooseValidator
export const createInvitationValidator: LooseValidator = {} as LooseValidator
export const upsertOrganizationSmtpValidator: LooseValidator = {} as LooseValidator
export const testOrganizationSmtpValidator: LooseValidator = {} as LooseValidator
export const createRoleValidator: LooseValidator = {} as LooseValidator
export const previewRoleUpdateValidator: LooseValidator = {} as LooseValidator
export const updateRoleValidator: LooseValidator = {} as LooseValidator
export const resetRoleValidator: LooseValidator = {} as LooseValidator
export const deleteRoleValidator: LooseValidator = {} as LooseValidator
export const assignMemberRoleValidator: LooseValidator = {} as LooseValidator
export const transferOwnershipValidator: LooseValidator = {} as LooseValidator
export const listTenantAuditValidator: LooseValidator = {} as LooseValidator
export const listContactsValidator: LooseValidator = {} as LooseValidator
export const createContactValidator: LooseValidator = {} as LooseValidator
export const importContactsValidator: LooseValidator = {} as LooseValidator
export const contactIdParamValidator: LooseValidator = {} as LooseValidator
export const updateContactValidator: LooseValidator = {} as LooseValidator
export const createTagValidator: LooseValidator = {} as LooseValidator
export const tagIdParamValidator: LooseValidator = {} as LooseValidator
export const assignTagContactValidator: LooseValidator = {} as LooseValidator
export const tagContactParamsValidator: LooseValidator = {} as LooseValidator
export const updateTagValidator: LooseValidator = {} as LooseValidator
export const createApiKeyValidator: LooseValidator = {} as LooseValidator
export const apiKeyIdParamValidator: LooseValidator = {} as LooseValidator
export const integrationProviderParamValidator: LooseValidator = {} as LooseValidator
export const upsertIntegrationConnectionValidator: LooseValidator = {} as LooseValidator
export const mediaUploadIdParamValidator: LooseValidator = {} as LooseValidator
export const initiateMediaUploadValidator: LooseValidator = {} as LooseValidator
export const listMediaLibraryValidator: LooseValidator = {} as LooseValidator
export const mediaAssetIdParamValidator: LooseValidator = {} as LooseValidator
export const listKnowledgeDocumentsValidator: LooseValidator = {} as LooseValidator
export const createKnowledgeDocumentValidator: LooseValidator = {} as LooseValidator
export const knowledgeDocumentIdParamValidator: LooseValidator = {} as LooseValidator
export const listFlowsValidator: LooseValidator = {} as LooseValidator
export const createFlowValidator: LooseValidator = {} as LooseValidator
export const flowIdParamValidator: LooseValidator = {} as LooseValidator
export const updateFlowValidator: LooseValidator = {} as LooseValidator
export const validateFlowValidator: LooseValidator = {} as LooseValidator
export const listCampaignsValidator: LooseValidator = {} as LooseValidator
export const campaignIdParamValidator: LooseValidator = {} as LooseValidator
export const previewCampaignValidator: LooseValidator = {} as LooseValidator
export const scheduleCampaignValidator: LooseValidator = {} as LooseValidator
export const createCampaignValidator: LooseValidator = {} as LooseValidator
export const updateCampaignValidator: LooseValidator = {} as LooseValidator
export const replaceCampaignRecipientsValidator: LooseValidator = {} as LooseValidator
export const listConversationsValidator: LooseValidator = {} as LooseValidator
export const createConversationValidator: LooseValidator = {} as LooseValidator
export const conversationIdParamValidator: LooseValidator = {} as LooseValidator
export const updateConversationValidator: LooseValidator = {} as LooseValidator
export const assignConversationValidator: LooseValidator = {} as LooseValidator
export const listMessagesValidator: LooseValidator = {} as LooseValidator
export const createMessageValidator: LooseValidator = {} as LooseValidator
export const createConversationNoteValidator: LooseValidator = {} as LooseValidator
export const billingCheckoutValidator: LooseValidator = {} as LooseValidator
export const billingVerifyValidator: LooseValidator = {} as LooseValidator
export const listNotificationsValidator: LooseValidator = {} as LooseValidator
export const notificationIdParamValidator: LooseValidator = {} as LooseValidator
