/* eslint-disable prettier/prettier */
import type { AdonisEndpoint } from '@tuyau/core/types'
import type { Registry } from './schema.d.ts'
import type { ApiDefinition } from './tree.d.ts'

const placeholder: any = {}

const routes = {
  'auth.sign_in_email': {
    methods: ["POST"],
    pattern: '/api/auth/sign-in/email',
    tokens: [{"old":"/api/auth/sign-in/email","type":0,"val":"api","end":""},{"old":"/api/auth/sign-in/email","type":0,"val":"auth","end":""},{"old":"/api/auth/sign-in/email","type":0,"val":"sign-in","end":""},{"old":"/api/auth/sign-in/email","type":0,"val":"email","end":""}],
    types: placeholder as Registry['auth.sign_in_email']['types'],
  },
  'auth.sign_out': {
    methods: ["POST"],
    pattern: '/api/auth/sign-out',
    tokens: [{"old":"/api/auth/sign-out","type":0,"val":"api","end":""},{"old":"/api/auth/sign-out","type":0,"val":"auth","end":""},{"old":"/api/auth/sign-out","type":0,"val":"sign-out","end":""}],
    types: placeholder as Registry['auth.sign_out']['types'],
  },
  'auth.get_session': {
    methods: ["GET","HEAD"],
    pattern: '/api/auth/get-session',
    tokens: [{"old":"/api/auth/get-session","type":0,"val":"api","end":""},{"old":"/api/auth/get-session","type":0,"val":"auth","end":""},{"old":"/api/auth/get-session","type":0,"val":"get-session","end":""}],
    types: placeholder as Registry['auth.get_session']['types'],
  },
  'auth.token': {
    methods: ["GET","HEAD"],
    pattern: '/api/auth/token',
    tokens: [{"old":"/api/auth/token","type":0,"val":"api","end":""},{"old":"/api/auth/token","type":0,"val":"auth","end":""},{"old":"/api/auth/token","type":0,"val":"token","end":""}],
    types: placeholder as Registry['auth.token']['types'],
  },
  'auth.jwks': {
    methods: ["GET","HEAD"],
    pattern: '/api/auth/jwks',
    tokens: [{"old":"/api/auth/jwks","type":0,"val":"api","end":""},{"old":"/api/auth/jwks","type":0,"val":"auth","end":""},{"old":"/api/auth/jwks","type":0,"val":"jwks","end":""}],
    types: placeholder as Registry['auth.jwks']['types'],
  },
  'media_public.serve': {
    methods: ["GET","HEAD"],
    pattern: '/media/*',
    tokens: [{"old":"/media/*","type":0,"val":"media","end":""},{"old":"/media/*","type":2,"val":"*","end":""}],
    types: placeholder as Registry['media_public.serve']['types'],
  },
  'whatsapp_webhook.verify': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/webhooks/whatsapp',
    tokens: [{"old":"/api/v1/webhooks/whatsapp","type":0,"val":"api","end":""},{"old":"/api/v1/webhooks/whatsapp","type":0,"val":"v1","end":""},{"old":"/api/v1/webhooks/whatsapp","type":0,"val":"webhooks","end":""},{"old":"/api/v1/webhooks/whatsapp","type":0,"val":"whatsapp","end":""}],
    types: placeholder as Registry['whatsapp_webhook.verify']['types'],
  },
  'whatsapp_webhook.receive': {
    methods: ["POST"],
    pattern: '/api/v1/webhooks/whatsapp',
    tokens: [{"old":"/api/v1/webhooks/whatsapp","type":0,"val":"api","end":""},{"old":"/api/v1/webhooks/whatsapp","type":0,"val":"v1","end":""},{"old":"/api/v1/webhooks/whatsapp","type":0,"val":"webhooks","end":""},{"old":"/api/v1/webhooks/whatsapp","type":0,"val":"whatsapp","end":""}],
    types: placeholder as Registry['whatsapp_webhook.receive']['types'],
  },
  'billing_razorpay_webhook.receive': {
    methods: ["POST"],
    pattern: '/api/v1/webhooks/billing/razorpay',
    tokens: [{"old":"/api/v1/webhooks/billing/razorpay","type":0,"val":"api","end":""},{"old":"/api/v1/webhooks/billing/razorpay","type":0,"val":"v1","end":""},{"old":"/api/v1/webhooks/billing/razorpay","type":0,"val":"webhooks","end":""},{"old":"/api/v1/webhooks/billing/razorpay","type":0,"val":"billing","end":""},{"old":"/api/v1/webhooks/billing/razorpay","type":0,"val":"razorpay","end":""}],
    types: placeholder as Registry['billing_razorpay_webhook.receive']['types'],
  },
  'demo_bookings.availability': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/demo/availability',
    tokens: [{"old":"/api/v1/demo/availability","type":0,"val":"api","end":""},{"old":"/api/v1/demo/availability","type":0,"val":"v1","end":""},{"old":"/api/v1/demo/availability","type":0,"val":"demo","end":""},{"old":"/api/v1/demo/availability","type":0,"val":"availability","end":""}],
    types: placeholder as Registry['demo_bookings.availability']['types'],
  },
  'demo_bookings.store': {
    methods: ["POST"],
    pattern: '/api/v1/demo/bookings',
    tokens: [{"old":"/api/v1/demo/bookings","type":0,"val":"api","end":""},{"old":"/api/v1/demo/bookings","type":0,"val":"v1","end":""},{"old":"/api/v1/demo/bookings","type":0,"val":"demo","end":""},{"old":"/api/v1/demo/bookings","type":0,"val":"bookings","end":""}],
    types: placeholder as Registry['demo_bookings.store']['types'],
  },
  'external_events.store': {
    methods: ["POST"],
    pattern: '/api/v1/integrations/events',
    tokens: [{"old":"/api/v1/integrations/events","type":0,"val":"api","end":""},{"old":"/api/v1/integrations/events","type":0,"val":"v1","end":""},{"old":"/api/v1/integrations/events","type":0,"val":"integrations","end":""},{"old":"/api/v1/integrations/events","type":0,"val":"events","end":""}],
    types: placeholder as Registry['external_events.store']['types'],
  },
  'shopenup_integrations.store': {
    methods: ["POST"],
    pattern: '/api/v1/integrations/shopenup/events',
    tokens: [{"old":"/api/v1/integrations/shopenup/events","type":0,"val":"api","end":""},{"old":"/api/v1/integrations/shopenup/events","type":0,"val":"v1","end":""},{"old":"/api/v1/integrations/shopenup/events","type":0,"val":"integrations","end":""},{"old":"/api/v1/integrations/shopenup/events","type":0,"val":"shopenup","end":""},{"old":"/api/v1/integrations/shopenup/events","type":0,"val":"events","end":""}],
    types: placeholder as Registry['shopenup_integrations.store']['types'],
  },
  'whatsapp_embedded_signup.session': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/whatsapp/embedded-signup/session',
    tokens: [{"old":"/api/v1/whatsapp/embedded-signup/session","type":0,"val":"api","end":""},{"old":"/api/v1/whatsapp/embedded-signup/session","type":0,"val":"v1","end":""},{"old":"/api/v1/whatsapp/embedded-signup/session","type":0,"val":"whatsapp","end":""},{"old":"/api/v1/whatsapp/embedded-signup/session","type":0,"val":"embedded-signup","end":""},{"old":"/api/v1/whatsapp/embedded-signup/session","type":0,"val":"session","end":""}],
    types: placeholder as Registry['whatsapp_embedded_signup.session']['types'],
  },
  'whatsapp_embedded_signup.complete': {
    methods: ["POST"],
    pattern: '/api/v1/whatsapp/embedded-signup/complete',
    tokens: [{"old":"/api/v1/whatsapp/embedded-signup/complete","type":0,"val":"api","end":""},{"old":"/api/v1/whatsapp/embedded-signup/complete","type":0,"val":"v1","end":""},{"old":"/api/v1/whatsapp/embedded-signup/complete","type":0,"val":"whatsapp","end":""},{"old":"/api/v1/whatsapp/embedded-signup/complete","type":0,"val":"embedded-signup","end":""},{"old":"/api/v1/whatsapp/embedded-signup/complete","type":0,"val":"complete","end":""}],
    types: placeholder as Registry['whatsapp_embedded_signup.complete']['types'],
  },
  'whatsapp_configs.index': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/whatsapp/configs',
    tokens: [{"old":"/api/v1/whatsapp/configs","type":0,"val":"api","end":""},{"old":"/api/v1/whatsapp/configs","type":0,"val":"v1","end":""},{"old":"/api/v1/whatsapp/configs","type":0,"val":"whatsapp","end":""},{"old":"/api/v1/whatsapp/configs","type":0,"val":"configs","end":""}],
    types: placeholder as Registry['whatsapp_configs.index']['types'],
  },
  'whatsapp_configs.destroy': {
    methods: ["DELETE"],
    pattern: '/api/v1/whatsapp/configs/:id',
    tokens: [{"old":"/api/v1/whatsapp/configs/:id","type":0,"val":"api","end":""},{"old":"/api/v1/whatsapp/configs/:id","type":0,"val":"v1","end":""},{"old":"/api/v1/whatsapp/configs/:id","type":0,"val":"whatsapp","end":""},{"old":"/api/v1/whatsapp/configs/:id","type":0,"val":"configs","end":""},{"old":"/api/v1/whatsapp/configs/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['whatsapp_configs.destroy']['types'],
  },
  'whatsapp_configs.show': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/whatsapp/configs/:id',
    tokens: [{"old":"/api/v1/whatsapp/configs/:id","type":0,"val":"api","end":""},{"old":"/api/v1/whatsapp/configs/:id","type":0,"val":"v1","end":""},{"old":"/api/v1/whatsapp/configs/:id","type":0,"val":"whatsapp","end":""},{"old":"/api/v1/whatsapp/configs/:id","type":0,"val":"configs","end":""},{"old":"/api/v1/whatsapp/configs/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['whatsapp_configs.show']['types'],
  },
  'whatsapp_configs.test': {
    methods: ["POST"],
    pattern: '/api/v1/whatsapp/configs/:id/test',
    tokens: [{"old":"/api/v1/whatsapp/configs/:id/test","type":0,"val":"api","end":""},{"old":"/api/v1/whatsapp/configs/:id/test","type":0,"val":"v1","end":""},{"old":"/api/v1/whatsapp/configs/:id/test","type":0,"val":"whatsapp","end":""},{"old":"/api/v1/whatsapp/configs/:id/test","type":0,"val":"configs","end":""},{"old":"/api/v1/whatsapp/configs/:id/test","type":1,"val":"id","end":""},{"old":"/api/v1/whatsapp/configs/:id/test","type":0,"val":"test","end":""}],
    types: placeholder as Registry['whatsapp_configs.test']['types'],
  },
  'message_templates.index': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/whatsapp/templates',
    tokens: [{"old":"/api/v1/whatsapp/templates","type":0,"val":"api","end":""},{"old":"/api/v1/whatsapp/templates","type":0,"val":"v1","end":""},{"old":"/api/v1/whatsapp/templates","type":0,"val":"whatsapp","end":""},{"old":"/api/v1/whatsapp/templates","type":0,"val":"templates","end":""}],
    types: placeholder as Registry['message_templates.index']['types'],
  },
  'message_templates.show': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/whatsapp/templates/:id',
    tokens: [{"old":"/api/v1/whatsapp/templates/:id","type":0,"val":"api","end":""},{"old":"/api/v1/whatsapp/templates/:id","type":0,"val":"v1","end":""},{"old":"/api/v1/whatsapp/templates/:id","type":0,"val":"whatsapp","end":""},{"old":"/api/v1/whatsapp/templates/:id","type":0,"val":"templates","end":""},{"old":"/api/v1/whatsapp/templates/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['message_templates.show']['types'],
  },
  'message_templates.store': {
    methods: ["POST"],
    pattern: '/api/v1/whatsapp/templates',
    tokens: [{"old":"/api/v1/whatsapp/templates","type":0,"val":"api","end":""},{"old":"/api/v1/whatsapp/templates","type":0,"val":"v1","end":""},{"old":"/api/v1/whatsapp/templates","type":0,"val":"whatsapp","end":""},{"old":"/api/v1/whatsapp/templates","type":0,"val":"templates","end":""}],
    types: placeholder as Registry['message_templates.store']['types'],
  },
  'message_templates.sync': {
    methods: ["POST"],
    pattern: '/api/v1/whatsapp/templates/sync',
    tokens: [{"old":"/api/v1/whatsapp/templates/sync","type":0,"val":"api","end":""},{"old":"/api/v1/whatsapp/templates/sync","type":0,"val":"v1","end":""},{"old":"/api/v1/whatsapp/templates/sync","type":0,"val":"whatsapp","end":""},{"old":"/api/v1/whatsapp/templates/sync","type":0,"val":"templates","end":""},{"old":"/api/v1/whatsapp/templates/sync","type":0,"val":"sync","end":""}],
    types: placeholder as Registry['message_templates.sync']['types'],
  },
  'message_templates.destroy': {
    methods: ["DELETE"],
    pattern: '/api/v1/whatsapp/templates/:id',
    tokens: [{"old":"/api/v1/whatsapp/templates/:id","type":0,"val":"api","end":""},{"old":"/api/v1/whatsapp/templates/:id","type":0,"val":"v1","end":""},{"old":"/api/v1/whatsapp/templates/:id","type":0,"val":"whatsapp","end":""},{"old":"/api/v1/whatsapp/templates/:id","type":0,"val":"templates","end":""},{"old":"/api/v1/whatsapp/templates/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['message_templates.destroy']['types'],
  },
  'pre_signup': {
    methods: ["POST"],
    pattern: '/api/v1/auth/pre-signup',
    tokens: [{"old":"/api/v1/auth/pre-signup","type":0,"val":"api","end":""},{"old":"/api/v1/auth/pre-signup","type":0,"val":"v1","end":""},{"old":"/api/v1/auth/pre-signup","type":0,"val":"auth","end":""},{"old":"/api/v1/auth/pre-signup","type":0,"val":"pre-signup","end":""}],
    types: placeholder as Registry['pre_signup']['types'],
  },
  'pre_signup.resend': {
    methods: ["POST"],
    pattern: '/api/v1/auth/pre-signup/resend',
    tokens: [{"old":"/api/v1/auth/pre-signup/resend","type":0,"val":"api","end":""},{"old":"/api/v1/auth/pre-signup/resend","type":0,"val":"v1","end":""},{"old":"/api/v1/auth/pre-signup/resend","type":0,"val":"auth","end":""},{"old":"/api/v1/auth/pre-signup/resend","type":0,"val":"pre-signup","end":""},{"old":"/api/v1/auth/pre-signup/resend","type":0,"val":"resend","end":""}],
    types: placeholder as Registry['pre_signup.resend']['types'],
  },
  'verify_signup': {
    methods: ["POST"],
    pattern: '/api/v1/auth/verify-signup',
    tokens: [{"old":"/api/v1/auth/verify-signup","type":0,"val":"api","end":""},{"old":"/api/v1/auth/verify-signup","type":0,"val":"v1","end":""},{"old":"/api/v1/auth/verify-signup","type":0,"val":"auth","end":""},{"old":"/api/v1/auth/verify-signup","type":0,"val":"verify-signup","end":""}],
    types: placeholder as Registry['verify_signup']['types'],
  },
  'profile.show': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/account/profile',
    tokens: [{"old":"/api/v1/account/profile","type":0,"val":"api","end":""},{"old":"/api/v1/account/profile","type":0,"val":"v1","end":""},{"old":"/api/v1/account/profile","type":0,"val":"account","end":""},{"old":"/api/v1/account/profile","type":0,"val":"profile","end":""}],
    types: placeholder as Registry['profile.show']['types'],
  },
  'super_admin_organizations.index': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/super-admin/organizations',
    tokens: [{"old":"/api/v1/super-admin/organizations","type":0,"val":"api","end":""},{"old":"/api/v1/super-admin/organizations","type":0,"val":"v1","end":""},{"old":"/api/v1/super-admin/organizations","type":0,"val":"super-admin","end":""},{"old":"/api/v1/super-admin/organizations","type":0,"val":"organizations","end":""}],
    types: placeholder as Registry['super_admin_organizations.index']['types'],
  },
  'super_admin_organizations.show': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/super-admin/organizations/:id',
    tokens: [{"old":"/api/v1/super-admin/organizations/:id","type":0,"val":"api","end":""},{"old":"/api/v1/super-admin/organizations/:id","type":0,"val":"v1","end":""},{"old":"/api/v1/super-admin/organizations/:id","type":0,"val":"super-admin","end":""},{"old":"/api/v1/super-admin/organizations/:id","type":0,"val":"organizations","end":""},{"old":"/api/v1/super-admin/organizations/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['super_admin_organizations.show']['types'],
  },
  'super_admin_organizations.update': {
    methods: ["PATCH"],
    pattern: '/api/v1/super-admin/organizations/:id',
    tokens: [{"old":"/api/v1/super-admin/organizations/:id","type":0,"val":"api","end":""},{"old":"/api/v1/super-admin/organizations/:id","type":0,"val":"v1","end":""},{"old":"/api/v1/super-admin/organizations/:id","type":0,"val":"super-admin","end":""},{"old":"/api/v1/super-admin/organizations/:id","type":0,"val":"organizations","end":""},{"old":"/api/v1/super-admin/organizations/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['super_admin_organizations.update']['types'],
  },
  'super_admin_organizations.suspend': {
    methods: ["POST"],
    pattern: '/api/v1/super-admin/organizations/:id/suspend',
    tokens: [{"old":"/api/v1/super-admin/organizations/:id/suspend","type":0,"val":"api","end":""},{"old":"/api/v1/super-admin/organizations/:id/suspend","type":0,"val":"v1","end":""},{"old":"/api/v1/super-admin/organizations/:id/suspend","type":0,"val":"super-admin","end":""},{"old":"/api/v1/super-admin/organizations/:id/suspend","type":0,"val":"organizations","end":""},{"old":"/api/v1/super-admin/organizations/:id/suspend","type":1,"val":"id","end":""},{"old":"/api/v1/super-admin/organizations/:id/suspend","type":0,"val":"suspend","end":""}],
    types: placeholder as Registry['super_admin_organizations.suspend']['types'],
  },
  'super_admin_organizations.activate': {
    methods: ["POST"],
    pattern: '/api/v1/super-admin/organizations/:id/activate',
    tokens: [{"old":"/api/v1/super-admin/organizations/:id/activate","type":0,"val":"api","end":""},{"old":"/api/v1/super-admin/organizations/:id/activate","type":0,"val":"v1","end":""},{"old":"/api/v1/super-admin/organizations/:id/activate","type":0,"val":"super-admin","end":""},{"old":"/api/v1/super-admin/organizations/:id/activate","type":0,"val":"organizations","end":""},{"old":"/api/v1/super-admin/organizations/:id/activate","type":1,"val":"id","end":""},{"old":"/api/v1/super-admin/organizations/:id/activate","type":0,"val":"activate","end":""}],
    types: placeholder as Registry['super_admin_organizations.activate']['types'],
  },
  'super_admin_organizations.soft_delete': {
    methods: ["DELETE"],
    pattern: '/api/v1/super-admin/organizations/:id',
    tokens: [{"old":"/api/v1/super-admin/organizations/:id","type":0,"val":"api","end":""},{"old":"/api/v1/super-admin/organizations/:id","type":0,"val":"v1","end":""},{"old":"/api/v1/super-admin/organizations/:id","type":0,"val":"super-admin","end":""},{"old":"/api/v1/super-admin/organizations/:id","type":0,"val":"organizations","end":""},{"old":"/api/v1/super-admin/organizations/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['super_admin_organizations.soft_delete']['types'],
  },
  'super_admin_subscriptions.index': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/super-admin/subscriptions',
    tokens: [{"old":"/api/v1/super-admin/subscriptions","type":0,"val":"api","end":""},{"old":"/api/v1/super-admin/subscriptions","type":0,"val":"v1","end":""},{"old":"/api/v1/super-admin/subscriptions","type":0,"val":"super-admin","end":""},{"old":"/api/v1/super-admin/subscriptions","type":0,"val":"subscriptions","end":""}],
    types: placeholder as Registry['super_admin_subscriptions.index']['types'],
  },
  'super_admin_subscriptions.store': {
    methods: ["POST"],
    pattern: '/api/v1/super-admin/subscriptions',
    tokens: [{"old":"/api/v1/super-admin/subscriptions","type":0,"val":"api","end":""},{"old":"/api/v1/super-admin/subscriptions","type":0,"val":"v1","end":""},{"old":"/api/v1/super-admin/subscriptions","type":0,"val":"super-admin","end":""},{"old":"/api/v1/super-admin/subscriptions","type":0,"val":"subscriptions","end":""}],
    types: placeholder as Registry['super_admin_subscriptions.store']['types'],
  },
  'super_admin_subscriptions.show': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/super-admin/subscriptions/:id',
    tokens: [{"old":"/api/v1/super-admin/subscriptions/:id","type":0,"val":"api","end":""},{"old":"/api/v1/super-admin/subscriptions/:id","type":0,"val":"v1","end":""},{"old":"/api/v1/super-admin/subscriptions/:id","type":0,"val":"super-admin","end":""},{"old":"/api/v1/super-admin/subscriptions/:id","type":0,"val":"subscriptions","end":""},{"old":"/api/v1/super-admin/subscriptions/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['super_admin_subscriptions.show']['types'],
  },
  'super_admin_subscriptions.update': {
    methods: ["PATCH"],
    pattern: '/api/v1/super-admin/subscriptions/:id',
    tokens: [{"old":"/api/v1/super-admin/subscriptions/:id","type":0,"val":"api","end":""},{"old":"/api/v1/super-admin/subscriptions/:id","type":0,"val":"v1","end":""},{"old":"/api/v1/super-admin/subscriptions/:id","type":0,"val":"super-admin","end":""},{"old":"/api/v1/super-admin/subscriptions/:id","type":0,"val":"subscriptions","end":""},{"old":"/api/v1/super-admin/subscriptions/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['super_admin_subscriptions.update']['types'],
  },
  'super_admin_subscriptions.soft_delete': {
    methods: ["DELETE"],
    pattern: '/api/v1/super-admin/subscriptions/:id',
    tokens: [{"old":"/api/v1/super-admin/subscriptions/:id","type":0,"val":"api","end":""},{"old":"/api/v1/super-admin/subscriptions/:id","type":0,"val":"v1","end":""},{"old":"/api/v1/super-admin/subscriptions/:id","type":0,"val":"super-admin","end":""},{"old":"/api/v1/super-admin/subscriptions/:id","type":0,"val":"subscriptions","end":""},{"old":"/api/v1/super-admin/subscriptions/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['super_admin_subscriptions.soft_delete']['types'],
  },
  'super_admin_plans.index': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/super-admin/plans',
    tokens: [{"old":"/api/v1/super-admin/plans","type":0,"val":"api","end":""},{"old":"/api/v1/super-admin/plans","type":0,"val":"v1","end":""},{"old":"/api/v1/super-admin/plans","type":0,"val":"super-admin","end":""},{"old":"/api/v1/super-admin/plans","type":0,"val":"plans","end":""}],
    types: placeholder as Registry['super_admin_plans.index']['types'],
  },
  'super_admin_plans.store': {
    methods: ["POST"],
    pattern: '/api/v1/super-admin/plans',
    tokens: [{"old":"/api/v1/super-admin/plans","type":0,"val":"api","end":""},{"old":"/api/v1/super-admin/plans","type":0,"val":"v1","end":""},{"old":"/api/v1/super-admin/plans","type":0,"val":"super-admin","end":""},{"old":"/api/v1/super-admin/plans","type":0,"val":"plans","end":""}],
    types: placeholder as Registry['super_admin_plans.store']['types'],
  },
  'super_admin_plans.show': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/super-admin/plans/:id',
    tokens: [{"old":"/api/v1/super-admin/plans/:id","type":0,"val":"api","end":""},{"old":"/api/v1/super-admin/plans/:id","type":0,"val":"v1","end":""},{"old":"/api/v1/super-admin/plans/:id","type":0,"val":"super-admin","end":""},{"old":"/api/v1/super-admin/plans/:id","type":0,"val":"plans","end":""},{"old":"/api/v1/super-admin/plans/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['super_admin_plans.show']['types'],
  },
  'super_admin_plans.update': {
    methods: ["PATCH"],
    pattern: '/api/v1/super-admin/plans/:id',
    tokens: [{"old":"/api/v1/super-admin/plans/:id","type":0,"val":"api","end":""},{"old":"/api/v1/super-admin/plans/:id","type":0,"val":"v1","end":""},{"old":"/api/v1/super-admin/plans/:id","type":0,"val":"super-admin","end":""},{"old":"/api/v1/super-admin/plans/:id","type":0,"val":"plans","end":""},{"old":"/api/v1/super-admin/plans/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['super_admin_plans.update']['types'],
  },
  'super_admin_plans.soft_delete': {
    methods: ["DELETE"],
    pattern: '/api/v1/super-admin/plans/:id',
    tokens: [{"old":"/api/v1/super-admin/plans/:id","type":0,"val":"api","end":""},{"old":"/api/v1/super-admin/plans/:id","type":0,"val":"v1","end":""},{"old":"/api/v1/super-admin/plans/:id","type":0,"val":"super-admin","end":""},{"old":"/api/v1/super-admin/plans/:id","type":0,"val":"plans","end":""},{"old":"/api/v1/super-admin/plans/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['super_admin_plans.soft_delete']['types'],
  },
  'super_admin_invoices.summary': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/super-admin/invoices/summary',
    tokens: [{"old":"/api/v1/super-admin/invoices/summary","type":0,"val":"api","end":""},{"old":"/api/v1/super-admin/invoices/summary","type":0,"val":"v1","end":""},{"old":"/api/v1/super-admin/invoices/summary","type":0,"val":"super-admin","end":""},{"old":"/api/v1/super-admin/invoices/summary","type":0,"val":"invoices","end":""},{"old":"/api/v1/super-admin/invoices/summary","type":0,"val":"summary","end":""}],
    types: placeholder as Registry['super_admin_invoices.summary']['types'],
  },
  'super_admin_invoices.billing_profile': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/super-admin/invoices/billing-profile',
    tokens: [{"old":"/api/v1/super-admin/invoices/billing-profile","type":0,"val":"api","end":""},{"old":"/api/v1/super-admin/invoices/billing-profile","type":0,"val":"v1","end":""},{"old":"/api/v1/super-admin/invoices/billing-profile","type":0,"val":"super-admin","end":""},{"old":"/api/v1/super-admin/invoices/billing-profile","type":0,"val":"invoices","end":""},{"old":"/api/v1/super-admin/invoices/billing-profile","type":0,"val":"billing-profile","end":""}],
    types: placeholder as Registry['super_admin_invoices.billing_profile']['types'],
  },
  'super_admin_invoices.index': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/super-admin/invoices',
    tokens: [{"old":"/api/v1/super-admin/invoices","type":0,"val":"api","end":""},{"old":"/api/v1/super-admin/invoices","type":0,"val":"v1","end":""},{"old":"/api/v1/super-admin/invoices","type":0,"val":"super-admin","end":""},{"old":"/api/v1/super-admin/invoices","type":0,"val":"invoices","end":""}],
    types: placeholder as Registry['super_admin_invoices.index']['types'],
  },
  'super_admin_invoices.store': {
    methods: ["POST"],
    pattern: '/api/v1/super-admin/invoices',
    tokens: [{"old":"/api/v1/super-admin/invoices","type":0,"val":"api","end":""},{"old":"/api/v1/super-admin/invoices","type":0,"val":"v1","end":""},{"old":"/api/v1/super-admin/invoices","type":0,"val":"super-admin","end":""},{"old":"/api/v1/super-admin/invoices","type":0,"val":"invoices","end":""}],
    types: placeholder as Registry['super_admin_invoices.store']['types'],
  },
  'super_admin_invoices.show': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/super-admin/invoices/:id',
    tokens: [{"old":"/api/v1/super-admin/invoices/:id","type":0,"val":"api","end":""},{"old":"/api/v1/super-admin/invoices/:id","type":0,"val":"v1","end":""},{"old":"/api/v1/super-admin/invoices/:id","type":0,"val":"super-admin","end":""},{"old":"/api/v1/super-admin/invoices/:id","type":0,"val":"invoices","end":""},{"old":"/api/v1/super-admin/invoices/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['super_admin_invoices.show']['types'],
  },
  'super_admin_invoices.mark_paid': {
    methods: ["POST"],
    pattern: '/api/v1/super-admin/invoices/:id/mark-paid',
    tokens: [{"old":"/api/v1/super-admin/invoices/:id/mark-paid","type":0,"val":"api","end":""},{"old":"/api/v1/super-admin/invoices/:id/mark-paid","type":0,"val":"v1","end":""},{"old":"/api/v1/super-admin/invoices/:id/mark-paid","type":0,"val":"super-admin","end":""},{"old":"/api/v1/super-admin/invoices/:id/mark-paid","type":0,"val":"invoices","end":""},{"old":"/api/v1/super-admin/invoices/:id/mark-paid","type":1,"val":"id","end":""},{"old":"/api/v1/super-admin/invoices/:id/mark-paid","type":0,"val":"mark-paid","end":""}],
    types: placeholder as Registry['super_admin_invoices.mark_paid']['types'],
  },
  'super_admin_invoices.regenerate': {
    methods: ["POST"],
    pattern: '/api/v1/super-admin/invoices/:id/regenerate',
    tokens: [{"old":"/api/v1/super-admin/invoices/:id/regenerate","type":0,"val":"api","end":""},{"old":"/api/v1/super-admin/invoices/:id/regenerate","type":0,"val":"v1","end":""},{"old":"/api/v1/super-admin/invoices/:id/regenerate","type":0,"val":"super-admin","end":""},{"old":"/api/v1/super-admin/invoices/:id/regenerate","type":0,"val":"invoices","end":""},{"old":"/api/v1/super-admin/invoices/:id/regenerate","type":1,"val":"id","end":""},{"old":"/api/v1/super-admin/invoices/:id/regenerate","type":0,"val":"regenerate","end":""}],
    types: placeholder as Registry['super_admin_invoices.regenerate']['types'],
  },
  'super_admin_invoices.send': {
    methods: ["POST"],
    pattern: '/api/v1/super-admin/invoices/:id/send',
    tokens: [{"old":"/api/v1/super-admin/invoices/:id/send","type":0,"val":"api","end":""},{"old":"/api/v1/super-admin/invoices/:id/send","type":0,"val":"v1","end":""},{"old":"/api/v1/super-admin/invoices/:id/send","type":0,"val":"super-admin","end":""},{"old":"/api/v1/super-admin/invoices/:id/send","type":0,"val":"invoices","end":""},{"old":"/api/v1/super-admin/invoices/:id/send","type":1,"val":"id","end":""},{"old":"/api/v1/super-admin/invoices/:id/send","type":0,"val":"send","end":""}],
    types: placeholder as Registry['super_admin_invoices.send']['types'],
  },
  'super_admin_invoices.download': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/super-admin/invoices/:id/download',
    tokens: [{"old":"/api/v1/super-admin/invoices/:id/download","type":0,"val":"api","end":""},{"old":"/api/v1/super-admin/invoices/:id/download","type":0,"val":"v1","end":""},{"old":"/api/v1/super-admin/invoices/:id/download","type":0,"val":"super-admin","end":""},{"old":"/api/v1/super-admin/invoices/:id/download","type":0,"val":"invoices","end":""},{"old":"/api/v1/super-admin/invoices/:id/download","type":1,"val":"id","end":""},{"old":"/api/v1/super-admin/invoices/:id/download","type":0,"val":"download","end":""}],
    types: placeholder as Registry['super_admin_invoices.download']['types'],
  },
  'super_admin_platform_settings.show': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/super-admin/platform-settings',
    tokens: [{"old":"/api/v1/super-admin/platform-settings","type":0,"val":"api","end":""},{"old":"/api/v1/super-admin/platform-settings","type":0,"val":"v1","end":""},{"old":"/api/v1/super-admin/platform-settings","type":0,"val":"super-admin","end":""},{"old":"/api/v1/super-admin/platform-settings","type":0,"val":"platform-settings","end":""}],
    types: placeholder as Registry['super_admin_platform_settings.show']['types'],
  },
  'super_admin_platform_settings.update': {
    methods: ["PATCH"],
    pattern: '/api/v1/super-admin/platform-settings',
    tokens: [{"old":"/api/v1/super-admin/platform-settings","type":0,"val":"api","end":""},{"old":"/api/v1/super-admin/platform-settings","type":0,"val":"v1","end":""},{"old":"/api/v1/super-admin/platform-settings","type":0,"val":"super-admin","end":""},{"old":"/api/v1/super-admin/platform-settings","type":0,"val":"platform-settings","end":""}],
    types: placeholder as Registry['super_admin_platform_settings.update']['types'],
  },
  'super_admin_ai_config.show': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/super-admin/ai-config',
    tokens: [{"old":"/api/v1/super-admin/ai-config","type":0,"val":"api","end":""},{"old":"/api/v1/super-admin/ai-config","type":0,"val":"v1","end":""},{"old":"/api/v1/super-admin/ai-config","type":0,"val":"super-admin","end":""},{"old":"/api/v1/super-admin/ai-config","type":0,"val":"ai-config","end":""}],
    types: placeholder as Registry['super_admin_ai_config.show']['types'],
  },
  'super_admin_ai_config.update': {
    methods: ["PATCH"],
    pattern: '/api/v1/super-admin/ai-config',
    tokens: [{"old":"/api/v1/super-admin/ai-config","type":0,"val":"api","end":""},{"old":"/api/v1/super-admin/ai-config","type":0,"val":"v1","end":""},{"old":"/api/v1/super-admin/ai-config","type":0,"val":"super-admin","end":""},{"old":"/api/v1/super-admin/ai-config","type":0,"val":"ai-config","end":""}],
    types: placeholder as Registry['super_admin_ai_config.update']['types'],
  },
  'super_admin_audit.index': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/super-admin/audit-logs',
    tokens: [{"old":"/api/v1/super-admin/audit-logs","type":0,"val":"api","end":""},{"old":"/api/v1/super-admin/audit-logs","type":0,"val":"v1","end":""},{"old":"/api/v1/super-admin/audit-logs","type":0,"val":"super-admin","end":""},{"old":"/api/v1/super-admin/audit-logs","type":0,"val":"audit-logs","end":""}],
    types: placeholder as Registry['super_admin_audit.index']['types'],
  },
  'super_admin_analytics.summary': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/super-admin/analytics/summary',
    tokens: [{"old":"/api/v1/super-admin/analytics/summary","type":0,"val":"api","end":""},{"old":"/api/v1/super-admin/analytics/summary","type":0,"val":"v1","end":""},{"old":"/api/v1/super-admin/analytics/summary","type":0,"val":"super-admin","end":""},{"old":"/api/v1/super-admin/analytics/summary","type":0,"val":"analytics","end":""},{"old":"/api/v1/super-admin/analytics/summary","type":0,"val":"summary","end":""}],
    types: placeholder as Registry['super_admin_analytics.summary']['types'],
  },
  'super_admin_platform_users.index': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/super-admin/platform-users',
    tokens: [{"old":"/api/v1/super-admin/platform-users","type":0,"val":"api","end":""},{"old":"/api/v1/super-admin/platform-users","type":0,"val":"v1","end":""},{"old":"/api/v1/super-admin/platform-users","type":0,"val":"super-admin","end":""},{"old":"/api/v1/super-admin/platform-users","type":0,"val":"platform-users","end":""}],
    types: placeholder as Registry['super_admin_platform_users.index']['types'],
  },
  'super_admin_search.index': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/super-admin/search',
    tokens: [{"old":"/api/v1/super-admin/search","type":0,"val":"api","end":""},{"old":"/api/v1/super-admin/search","type":0,"val":"v1","end":""},{"old":"/api/v1/super-admin/search","type":0,"val":"super-admin","end":""},{"old":"/api/v1/super-admin/search","type":0,"val":"search","end":""}],
    types: placeholder as Registry['super_admin_search.index']['types'],
  },
  'organization_admin_users.index': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/organization-admin/users',
    tokens: [{"old":"/api/v1/organization-admin/users","type":0,"val":"api","end":""},{"old":"/api/v1/organization-admin/users","type":0,"val":"v1","end":""},{"old":"/api/v1/organization-admin/users","type":0,"val":"organization-admin","end":""},{"old":"/api/v1/organization-admin/users","type":0,"val":"users","end":""}],
    types: placeholder as Registry['organization_admin_users.index']['types'],
  },
  'organization_admin_users.show': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/organization-admin/users/:id',
    tokens: [{"old":"/api/v1/organization-admin/users/:id","type":0,"val":"api","end":""},{"old":"/api/v1/organization-admin/users/:id","type":0,"val":"v1","end":""},{"old":"/api/v1/organization-admin/users/:id","type":0,"val":"organization-admin","end":""},{"old":"/api/v1/organization-admin/users/:id","type":0,"val":"users","end":""},{"old":"/api/v1/organization-admin/users/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['organization_admin_users.show']['types'],
  },
  'organization_admin_users.update': {
    methods: ["PATCH"],
    pattern: '/api/v1/organization-admin/users/:id',
    tokens: [{"old":"/api/v1/organization-admin/users/:id","type":0,"val":"api","end":""},{"old":"/api/v1/organization-admin/users/:id","type":0,"val":"v1","end":""},{"old":"/api/v1/organization-admin/users/:id","type":0,"val":"organization-admin","end":""},{"old":"/api/v1/organization-admin/users/:id","type":0,"val":"users","end":""},{"old":"/api/v1/organization-admin/users/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['organization_admin_users.update']['types'],
  },
  'organization_admin_users.soft_delete': {
    methods: ["DELETE"],
    pattern: '/api/v1/organization-admin/users/:id',
    tokens: [{"old":"/api/v1/organization-admin/users/:id","type":0,"val":"api","end":""},{"old":"/api/v1/organization-admin/users/:id","type":0,"val":"v1","end":""},{"old":"/api/v1/organization-admin/users/:id","type":0,"val":"organization-admin","end":""},{"old":"/api/v1/organization-admin/users/:id","type":0,"val":"users","end":""},{"old":"/api/v1/organization-admin/users/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['organization_admin_users.soft_delete']['types'],
  },
  'organizations.store': {
    methods: ["POST"],
    pattern: '/api/v1/organizations',
    tokens: [{"old":"/api/v1/organizations","type":0,"val":"api","end":""},{"old":"/api/v1/organizations","type":0,"val":"v1","end":""},{"old":"/api/v1/organizations","type":0,"val":"organizations","end":""}],
    types: placeholder as Registry['organizations.store']['types'],
  },
  'organizations.index': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/organizations',
    tokens: [{"old":"/api/v1/organizations","type":0,"val":"api","end":""},{"old":"/api/v1/organizations","type":0,"val":"v1","end":""},{"old":"/api/v1/organizations","type":0,"val":"organizations","end":""}],
    types: placeholder as Registry['organizations.index']['types'],
  },
  'organizations.set_active': {
    methods: ["POST"],
    pattern: '/api/v1/organizations/:id/set-active',
    tokens: [{"old":"/api/v1/organizations/:id/set-active","type":0,"val":"api","end":""},{"old":"/api/v1/organizations/:id/set-active","type":0,"val":"v1","end":""},{"old":"/api/v1/organizations/:id/set-active","type":0,"val":"organizations","end":""},{"old":"/api/v1/organizations/:id/set-active","type":1,"val":"id","end":""},{"old":"/api/v1/organizations/:id/set-active","type":0,"val":"set-active","end":""}],
    types: placeholder as Registry['organizations.set_active']['types'],
  },
  'organizations.update': {
    methods: ["PATCH"],
    pattern: '/api/v1/organizations/:id',
    tokens: [{"old":"/api/v1/organizations/:id","type":0,"val":"api","end":""},{"old":"/api/v1/organizations/:id","type":0,"val":"v1","end":""},{"old":"/api/v1/organizations/:id","type":0,"val":"organizations","end":""},{"old":"/api/v1/organizations/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['organizations.update']['types'],
  },
  'organizations.destroy': {
    methods: ["DELETE"],
    pattern: '/api/v1/organizations/:id',
    tokens: [{"old":"/api/v1/organizations/:id","type":0,"val":"api","end":""},{"old":"/api/v1/organizations/:id","type":0,"val":"v1","end":""},{"old":"/api/v1/organizations/:id","type":0,"val":"organizations","end":""},{"old":"/api/v1/organizations/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['organizations.destroy']['types'],
  },
  'invitations.store': {
    methods: ["POST"],
    pattern: '/api/v1/organizations/:id/invitations',
    tokens: [{"old":"/api/v1/organizations/:id/invitations","type":0,"val":"api","end":""},{"old":"/api/v1/organizations/:id/invitations","type":0,"val":"v1","end":""},{"old":"/api/v1/organizations/:id/invitations","type":0,"val":"organizations","end":""},{"old":"/api/v1/organizations/:id/invitations","type":1,"val":"id","end":""},{"old":"/api/v1/organizations/:id/invitations","type":0,"val":"invitations","end":""}],
    types: placeholder as Registry['invitations.store']['types'],
  },
  'organization_smtp.show': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/organizations/:id/smtp',
    tokens: [{"old":"/api/v1/organizations/:id/smtp","type":0,"val":"api","end":""},{"old":"/api/v1/organizations/:id/smtp","type":0,"val":"v1","end":""},{"old":"/api/v1/organizations/:id/smtp","type":0,"val":"organizations","end":""},{"old":"/api/v1/organizations/:id/smtp","type":1,"val":"id","end":""},{"old":"/api/v1/organizations/:id/smtp","type":0,"val":"smtp","end":""}],
    types: placeholder as Registry['organization_smtp.show']['types'],
  },
  'organization_smtp.update': {
    methods: ["PUT"],
    pattern: '/api/v1/organizations/:id/smtp',
    tokens: [{"old":"/api/v1/organizations/:id/smtp","type":0,"val":"api","end":""},{"old":"/api/v1/organizations/:id/smtp","type":0,"val":"v1","end":""},{"old":"/api/v1/organizations/:id/smtp","type":0,"val":"organizations","end":""},{"old":"/api/v1/organizations/:id/smtp","type":1,"val":"id","end":""},{"old":"/api/v1/organizations/:id/smtp","type":0,"val":"smtp","end":""}],
    types: placeholder as Registry['organization_smtp.update']['types'],
  },
  'organization_smtp.test': {
    methods: ["POST"],
    pattern: '/api/v1/organizations/:id/smtp/test',
    tokens: [{"old":"/api/v1/organizations/:id/smtp/test","type":0,"val":"api","end":""},{"old":"/api/v1/organizations/:id/smtp/test","type":0,"val":"v1","end":""},{"old":"/api/v1/organizations/:id/smtp/test","type":0,"val":"organizations","end":""},{"old":"/api/v1/organizations/:id/smtp/test","type":1,"val":"id","end":""},{"old":"/api/v1/organizations/:id/smtp/test","type":0,"val":"smtp","end":""},{"old":"/api/v1/organizations/:id/smtp/test","type":0,"val":"test","end":""}],
    types: placeholder as Registry['organization_smtp.test']['types'],
  },
  'organization_smtp.destroy': {
    methods: ["DELETE"],
    pattern: '/api/v1/organizations/:id/smtp',
    tokens: [{"old":"/api/v1/organizations/:id/smtp","type":0,"val":"api","end":""},{"old":"/api/v1/organizations/:id/smtp","type":0,"val":"v1","end":""},{"old":"/api/v1/organizations/:id/smtp","type":0,"val":"organizations","end":""},{"old":"/api/v1/organizations/:id/smtp","type":1,"val":"id","end":""},{"old":"/api/v1/organizations/:id/smtp","type":0,"val":"smtp","end":""}],
    types: placeholder as Registry['organization_smtp.destroy']['types'],
  },
  'access_context.show': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/access-context',
    tokens: [{"old":"/api/v1/access-context","type":0,"val":"api","end":""},{"old":"/api/v1/access-context","type":0,"val":"v1","end":""},{"old":"/api/v1/access-context","type":0,"val":"access-context","end":""}],
    types: placeholder as Registry['access_context.show']['types'],
  },
  'global_search.index': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/search',
    tokens: [{"old":"/api/v1/search","type":0,"val":"api","end":""},{"old":"/api/v1/search","type":0,"val":"v1","end":""},{"old":"/api/v1/search","type":0,"val":"search","end":""}],
    types: placeholder as Registry['global_search.index']['types'],
  },
  'onboarding.show': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/onboarding/state',
    tokens: [{"old":"/api/v1/onboarding/state","type":0,"val":"api","end":""},{"old":"/api/v1/onboarding/state","type":0,"val":"v1","end":""},{"old":"/api/v1/onboarding/state","type":0,"val":"onboarding","end":""},{"old":"/api/v1/onboarding/state","type":0,"val":"state","end":""}],
    types: placeholder as Registry['onboarding.show']['types'],
  },
  'roles.index': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/roles',
    tokens: [{"old":"/api/v1/roles","type":0,"val":"api","end":""},{"old":"/api/v1/roles","type":0,"val":"v1","end":""},{"old":"/api/v1/roles","type":0,"val":"roles","end":""}],
    types: placeholder as Registry['roles.index']['types'],
  },
  'roles.create': {
    methods: ["POST"],
    pattern: '/api/v1/roles',
    tokens: [{"old":"/api/v1/roles","type":0,"val":"api","end":""},{"old":"/api/v1/roles","type":0,"val":"v1","end":""},{"old":"/api/v1/roles","type":0,"val":"roles","end":""}],
    types: placeholder as Registry['roles.create']['types'],
  },
  'roles.preview': {
    methods: ["POST"],
    pattern: '/api/v1/roles/:roleKey/preview',
    tokens: [{"old":"/api/v1/roles/:roleKey/preview","type":0,"val":"api","end":""},{"old":"/api/v1/roles/:roleKey/preview","type":0,"val":"v1","end":""},{"old":"/api/v1/roles/:roleKey/preview","type":0,"val":"roles","end":""},{"old":"/api/v1/roles/:roleKey/preview","type":1,"val":"roleKey","end":""},{"old":"/api/v1/roles/:roleKey/preview","type":0,"val":"preview","end":""}],
    types: placeholder as Registry['roles.preview']['types'],
  },
  'roles.update': {
    methods: ["PUT"],
    pattern: '/api/v1/roles/:roleKey',
    tokens: [{"old":"/api/v1/roles/:roleKey","type":0,"val":"api","end":""},{"old":"/api/v1/roles/:roleKey","type":0,"val":"v1","end":""},{"old":"/api/v1/roles/:roleKey","type":0,"val":"roles","end":""},{"old":"/api/v1/roles/:roleKey","type":1,"val":"roleKey","end":""}],
    types: placeholder as Registry['roles.update']['types'],
  },
  'roles.reset': {
    methods: ["POST"],
    pattern: '/api/v1/roles/:roleKey/reset',
    tokens: [{"old":"/api/v1/roles/:roleKey/reset","type":0,"val":"api","end":""},{"old":"/api/v1/roles/:roleKey/reset","type":0,"val":"v1","end":""},{"old":"/api/v1/roles/:roleKey/reset","type":0,"val":"roles","end":""},{"old":"/api/v1/roles/:roleKey/reset","type":1,"val":"roleKey","end":""},{"old":"/api/v1/roles/:roleKey/reset","type":0,"val":"reset","end":""}],
    types: placeholder as Registry['roles.reset']['types'],
  },
  'roles.destroy': {
    methods: ["DELETE"],
    pattern: '/api/v1/roles/:roleKey',
    tokens: [{"old":"/api/v1/roles/:roleKey","type":0,"val":"api","end":""},{"old":"/api/v1/roles/:roleKey","type":0,"val":"v1","end":""},{"old":"/api/v1/roles/:roleKey","type":0,"val":"roles","end":""},{"old":"/api/v1/roles/:roleKey","type":1,"val":"roleKey","end":""}],
    types: placeholder as Registry['roles.destroy']['types'],
  },
  'members.index': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/members',
    tokens: [{"old":"/api/v1/members","type":0,"val":"api","end":""},{"old":"/api/v1/members","type":0,"val":"v1","end":""},{"old":"/api/v1/members","type":0,"val":"members","end":""}],
    types: placeholder as Registry['members.index']['types'],
  },
  'members.assign_role': {
    methods: ["PATCH"],
    pattern: '/api/v1/members/:memberId/role',
    tokens: [{"old":"/api/v1/members/:memberId/role","type":0,"val":"api","end":""},{"old":"/api/v1/members/:memberId/role","type":0,"val":"v1","end":""},{"old":"/api/v1/members/:memberId/role","type":0,"val":"members","end":""},{"old":"/api/v1/members/:memberId/role","type":1,"val":"memberId","end":""},{"old":"/api/v1/members/:memberId/role","type":0,"val":"role","end":""}],
    types: placeholder as Registry['members.assign_role']['types'],
  },
  'members.resend_invite': {
    methods: ["POST"],
    pattern: '/api/v1/members/:memberId/resend-invite',
    tokens: [{"old":"/api/v1/members/:memberId/resend-invite","type":0,"val":"api","end":""},{"old":"/api/v1/members/:memberId/resend-invite","type":0,"val":"v1","end":""},{"old":"/api/v1/members/:memberId/resend-invite","type":0,"val":"members","end":""},{"old":"/api/v1/members/:memberId/resend-invite","type":1,"val":"memberId","end":""},{"old":"/api/v1/members/:memberId/resend-invite","type":0,"val":"resend-invite","end":""}],
    types: placeholder as Registry['members.resend_invite']['types'],
  },
  'members.remove': {
    methods: ["DELETE"],
    pattern: '/api/v1/members/:memberId',
    tokens: [{"old":"/api/v1/members/:memberId","type":0,"val":"api","end":""},{"old":"/api/v1/members/:memberId","type":0,"val":"v1","end":""},{"old":"/api/v1/members/:memberId","type":0,"val":"members","end":""},{"old":"/api/v1/members/:memberId","type":1,"val":"memberId","end":""}],
    types: placeholder as Registry['members.remove']['types'],
  },
  'ownership.transfer': {
    methods: ["POST"],
    pattern: '/api/v1/ownership/transfer',
    tokens: [{"old":"/api/v1/ownership/transfer","type":0,"val":"api","end":""},{"old":"/api/v1/ownership/transfer","type":0,"val":"v1","end":""},{"old":"/api/v1/ownership/transfer","type":0,"val":"ownership","end":""},{"old":"/api/v1/ownership/transfer","type":0,"val":"transfer","end":""}],
    types: placeholder as Registry['ownership.transfer']['types'],
  },
  'audit.index': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/audit',
    tokens: [{"old":"/api/v1/audit","type":0,"val":"api","end":""},{"old":"/api/v1/audit","type":0,"val":"v1","end":""},{"old":"/api/v1/audit","type":0,"val":"audit","end":""}],
    types: placeholder as Registry['audit.index']['types'],
  },
  'analytics.summary': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/analytics/summary',
    tokens: [{"old":"/api/v1/analytics/summary","type":0,"val":"api","end":""},{"old":"/api/v1/analytics/summary","type":0,"val":"v1","end":""},{"old":"/api/v1/analytics/summary","type":0,"val":"analytics","end":""},{"old":"/api/v1/analytics/summary","type":0,"val":"summary","end":""}],
    types: placeholder as Registry['analytics.summary']['types'],
  },
  'contacts.index': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/contacts',
    tokens: [{"old":"/api/v1/contacts","type":0,"val":"api","end":""},{"old":"/api/v1/contacts","type":0,"val":"v1","end":""},{"old":"/api/v1/contacts","type":0,"val":"contacts","end":""}],
    types: placeholder as Registry['contacts.index']['types'],
  },
  'contacts.store': {
    methods: ["POST"],
    pattern: '/api/v1/contacts',
    tokens: [{"old":"/api/v1/contacts","type":0,"val":"api","end":""},{"old":"/api/v1/contacts","type":0,"val":"v1","end":""},{"old":"/api/v1/contacts","type":0,"val":"contacts","end":""}],
    types: placeholder as Registry['contacts.store']['types'],
  },
  'contacts.import_csv': {
    methods: ["POST"],
    pattern: '/api/v1/contacts/import',
    tokens: [{"old":"/api/v1/contacts/import","type":0,"val":"api","end":""},{"old":"/api/v1/contacts/import","type":0,"val":"v1","end":""},{"old":"/api/v1/contacts/import","type":0,"val":"contacts","end":""},{"old":"/api/v1/contacts/import","type":0,"val":"import","end":""}],
    types: placeholder as Registry['contacts.import_csv']['types'],
  },
  'contacts.show_import': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/contacts/import/:id',
    tokens: [{"old":"/api/v1/contacts/import/:id","type":0,"val":"api","end":""},{"old":"/api/v1/contacts/import/:id","type":0,"val":"v1","end":""},{"old":"/api/v1/contacts/import/:id","type":0,"val":"contacts","end":""},{"old":"/api/v1/contacts/import/:id","type":0,"val":"import","end":""},{"old":"/api/v1/contacts/import/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['contacts.show_import']['types'],
  },
  'contacts.show': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/contacts/:id',
    tokens: [{"old":"/api/v1/contacts/:id","type":0,"val":"api","end":""},{"old":"/api/v1/contacts/:id","type":0,"val":"v1","end":""},{"old":"/api/v1/contacts/:id","type":0,"val":"contacts","end":""},{"old":"/api/v1/contacts/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['contacts.show']['types'],
  },
  'contacts.update': {
    methods: ["PATCH"],
    pattern: '/api/v1/contacts/:id',
    tokens: [{"old":"/api/v1/contacts/:id","type":0,"val":"api","end":""},{"old":"/api/v1/contacts/:id","type":0,"val":"v1","end":""},{"old":"/api/v1/contacts/:id","type":0,"val":"contacts","end":""},{"old":"/api/v1/contacts/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['contacts.update']['types'],
  },
  'contacts.soft_delete': {
    methods: ["DELETE"],
    pattern: '/api/v1/contacts/:id',
    tokens: [{"old":"/api/v1/contacts/:id","type":0,"val":"api","end":""},{"old":"/api/v1/contacts/:id","type":0,"val":"v1","end":""},{"old":"/api/v1/contacts/:id","type":0,"val":"contacts","end":""},{"old":"/api/v1/contacts/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['contacts.soft_delete']['types'],
  },
  'tags.index': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/tags',
    tokens: [{"old":"/api/v1/tags","type":0,"val":"api","end":""},{"old":"/api/v1/tags","type":0,"val":"v1","end":""},{"old":"/api/v1/tags","type":0,"val":"tags","end":""}],
    types: placeholder as Registry['tags.index']['types'],
  },
  'tags.store': {
    methods: ["POST"],
    pattern: '/api/v1/tags',
    tokens: [{"old":"/api/v1/tags","type":0,"val":"api","end":""},{"old":"/api/v1/tags","type":0,"val":"v1","end":""},{"old":"/api/v1/tags","type":0,"val":"tags","end":""}],
    types: placeholder as Registry['tags.store']['types'],
  },
  'tags.contacts': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/tags/:id/contacts',
    tokens: [{"old":"/api/v1/tags/:id/contacts","type":0,"val":"api","end":""},{"old":"/api/v1/tags/:id/contacts","type":0,"val":"v1","end":""},{"old":"/api/v1/tags/:id/contacts","type":0,"val":"tags","end":""},{"old":"/api/v1/tags/:id/contacts","type":1,"val":"id","end":""},{"old":"/api/v1/tags/:id/contacts","type":0,"val":"contacts","end":""}],
    types: placeholder as Registry['tags.contacts']['types'],
  },
  'tags.assign_contact': {
    methods: ["POST"],
    pattern: '/api/v1/tags/:id/contacts',
    tokens: [{"old":"/api/v1/tags/:id/contacts","type":0,"val":"api","end":""},{"old":"/api/v1/tags/:id/contacts","type":0,"val":"v1","end":""},{"old":"/api/v1/tags/:id/contacts","type":0,"val":"tags","end":""},{"old":"/api/v1/tags/:id/contacts","type":1,"val":"id","end":""},{"old":"/api/v1/tags/:id/contacts","type":0,"val":"contacts","end":""}],
    types: placeholder as Registry['tags.assign_contact']['types'],
  },
  'tags.remove_contact': {
    methods: ["DELETE"],
    pattern: '/api/v1/tags/:id/contacts/:contactId',
    tokens: [{"old":"/api/v1/tags/:id/contacts/:contactId","type":0,"val":"api","end":""},{"old":"/api/v1/tags/:id/contacts/:contactId","type":0,"val":"v1","end":""},{"old":"/api/v1/tags/:id/contacts/:contactId","type":0,"val":"tags","end":""},{"old":"/api/v1/tags/:id/contacts/:contactId","type":1,"val":"id","end":""},{"old":"/api/v1/tags/:id/contacts/:contactId","type":0,"val":"contacts","end":""},{"old":"/api/v1/tags/:id/contacts/:contactId","type":1,"val":"contactId","end":""}],
    types: placeholder as Registry['tags.remove_contact']['types'],
  },
  'tags.show': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/tags/:id',
    tokens: [{"old":"/api/v1/tags/:id","type":0,"val":"api","end":""},{"old":"/api/v1/tags/:id","type":0,"val":"v1","end":""},{"old":"/api/v1/tags/:id","type":0,"val":"tags","end":""},{"old":"/api/v1/tags/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['tags.show']['types'],
  },
  'tags.update': {
    methods: ["PATCH"],
    pattern: '/api/v1/tags/:id',
    tokens: [{"old":"/api/v1/tags/:id","type":0,"val":"api","end":""},{"old":"/api/v1/tags/:id","type":0,"val":"v1","end":""},{"old":"/api/v1/tags/:id","type":0,"val":"tags","end":""},{"old":"/api/v1/tags/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['tags.update']['types'],
  },
  'tags.destroy': {
    methods: ["DELETE"],
    pattern: '/api/v1/tags/:id',
    tokens: [{"old":"/api/v1/tags/:id","type":0,"val":"api","end":""},{"old":"/api/v1/tags/:id","type":0,"val":"v1","end":""},{"old":"/api/v1/tags/:id","type":0,"val":"tags","end":""},{"old":"/api/v1/tags/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['tags.destroy']['types'],
  },
  'api_keys.index': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/api-keys',
    tokens: [{"old":"/api/v1/api-keys","type":0,"val":"api","end":""},{"old":"/api/v1/api-keys","type":0,"val":"v1","end":""},{"old":"/api/v1/api-keys","type":0,"val":"api-keys","end":""}],
    types: placeholder as Registry['api_keys.index']['types'],
  },
  'api_keys.store': {
    methods: ["POST"],
    pattern: '/api/v1/api-keys',
    tokens: [{"old":"/api/v1/api-keys","type":0,"val":"api","end":""},{"old":"/api/v1/api-keys","type":0,"val":"v1","end":""},{"old":"/api/v1/api-keys","type":0,"val":"api-keys","end":""}],
    types: placeholder as Registry['api_keys.store']['types'],
  },
  'api_keys.revoke': {
    methods: ["POST"],
    pattern: '/api/v1/api-keys/:id/revoke',
    tokens: [{"old":"/api/v1/api-keys/:id/revoke","type":0,"val":"api","end":""},{"old":"/api/v1/api-keys/:id/revoke","type":0,"val":"v1","end":""},{"old":"/api/v1/api-keys/:id/revoke","type":0,"val":"api-keys","end":""},{"old":"/api/v1/api-keys/:id/revoke","type":1,"val":"id","end":""},{"old":"/api/v1/api-keys/:id/revoke","type":0,"val":"revoke","end":""}],
    types: placeholder as Registry['api_keys.revoke']['types'],
  },
  'integration_connections.index': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/integrations',
    tokens: [{"old":"/api/v1/integrations","type":0,"val":"api","end":""},{"old":"/api/v1/integrations","type":0,"val":"v1","end":""},{"old":"/api/v1/integrations","type":0,"val":"integrations","end":""}],
    types: placeholder as Registry['integration_connections.index']['types'],
  },
  'integration_connections.show': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/integrations/:provider',
    tokens: [{"old":"/api/v1/integrations/:provider","type":0,"val":"api","end":""},{"old":"/api/v1/integrations/:provider","type":0,"val":"v1","end":""},{"old":"/api/v1/integrations/:provider","type":0,"val":"integrations","end":""},{"old":"/api/v1/integrations/:provider","type":1,"val":"provider","end":""}],
    types: placeholder as Registry['integration_connections.show']['types'],
  },
  'integration_connections.upsert': {
    methods: ["PUT"],
    pattern: '/api/v1/integrations/:provider',
    tokens: [{"old":"/api/v1/integrations/:provider","type":0,"val":"api","end":""},{"old":"/api/v1/integrations/:provider","type":0,"val":"v1","end":""},{"old":"/api/v1/integrations/:provider","type":0,"val":"integrations","end":""},{"old":"/api/v1/integrations/:provider","type":1,"val":"provider","end":""}],
    types: placeholder as Registry['integration_connections.upsert']['types'],
  },
  'integration_connections.destroy': {
    methods: ["DELETE"],
    pattern: '/api/v1/integrations/:provider',
    tokens: [{"old":"/api/v1/integrations/:provider","type":0,"val":"api","end":""},{"old":"/api/v1/integrations/:provider","type":0,"val":"v1","end":""},{"old":"/api/v1/integrations/:provider","type":0,"val":"integrations","end":""},{"old":"/api/v1/integrations/:provider","type":1,"val":"provider","end":""}],
    types: placeholder as Registry['integration_connections.destroy']['types'],
  },
  'media_uploads.put_content': {
    methods: ["PUT"],
    pattern: '/api/v1/media/uploads/:id/content',
    tokens: [{"old":"/api/v1/media/uploads/:id/content","type":0,"val":"api","end":""},{"old":"/api/v1/media/uploads/:id/content","type":0,"val":"v1","end":""},{"old":"/api/v1/media/uploads/:id/content","type":0,"val":"media","end":""},{"old":"/api/v1/media/uploads/:id/content","type":0,"val":"uploads","end":""},{"old":"/api/v1/media/uploads/:id/content","type":1,"val":"id","end":""},{"old":"/api/v1/media/uploads/:id/content","type":0,"val":"content","end":""}],
    types: placeholder as Registry['media_uploads.put_content']['types'],
  },
  'media_assets.organization_logo': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/media/organization-logo',
    tokens: [{"old":"/api/v1/media/organization-logo","type":0,"val":"api","end":""},{"old":"/api/v1/media/organization-logo","type":0,"val":"v1","end":""},{"old":"/api/v1/media/organization-logo","type":0,"val":"media","end":""},{"old":"/api/v1/media/organization-logo","type":0,"val":"organization-logo","end":""}],
    types: placeholder as Registry['media_assets.organization_logo']['types'],
  },
  'media_uploads.store': {
    methods: ["POST"],
    pattern: '/api/v1/media/uploads',
    tokens: [{"old":"/api/v1/media/uploads","type":0,"val":"api","end":""},{"old":"/api/v1/media/uploads","type":0,"val":"v1","end":""},{"old":"/api/v1/media/uploads","type":0,"val":"media","end":""},{"old":"/api/v1/media/uploads","type":0,"val":"uploads","end":""}],
    types: placeholder as Registry['media_uploads.store']['types'],
  },
  'media_uploads.complete': {
    methods: ["POST"],
    pattern: '/api/v1/media/uploads/:id/complete',
    tokens: [{"old":"/api/v1/media/uploads/:id/complete","type":0,"val":"api","end":""},{"old":"/api/v1/media/uploads/:id/complete","type":0,"val":"v1","end":""},{"old":"/api/v1/media/uploads/:id/complete","type":0,"val":"media","end":""},{"old":"/api/v1/media/uploads/:id/complete","type":0,"val":"uploads","end":""},{"old":"/api/v1/media/uploads/:id/complete","type":1,"val":"id","end":""},{"old":"/api/v1/media/uploads/:id/complete","type":0,"val":"complete","end":""}],
    types: placeholder as Registry['media_uploads.complete']['types'],
  },
  'media_assets.index': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/media',
    tokens: [{"old":"/api/v1/media","type":0,"val":"api","end":""},{"old":"/api/v1/media","type":0,"val":"v1","end":""},{"old":"/api/v1/media","type":0,"val":"media","end":""}],
    types: placeholder as Registry['media_assets.index']['types'],
  },
  'media_assets.quota': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/media/quota',
    tokens: [{"old":"/api/v1/media/quota","type":0,"val":"api","end":""},{"old":"/api/v1/media/quota","type":0,"val":"v1","end":""},{"old":"/api/v1/media/quota","type":0,"val":"media","end":""},{"old":"/api/v1/media/quota","type":0,"val":"quota","end":""}],
    types: placeholder as Registry['media_assets.quota']['types'],
  },
  'media_assets.show': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/media/:id',
    tokens: [{"old":"/api/v1/media/:id","type":0,"val":"api","end":""},{"old":"/api/v1/media/:id","type":0,"val":"v1","end":""},{"old":"/api/v1/media/:id","type":0,"val":"media","end":""},{"old":"/api/v1/media/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['media_assets.show']['types'],
  },
  'media_assets.destroy': {
    methods: ["DELETE"],
    pattern: '/api/v1/media/:id',
    tokens: [{"old":"/api/v1/media/:id","type":0,"val":"api","end":""},{"old":"/api/v1/media/:id","type":0,"val":"v1","end":""},{"old":"/api/v1/media/:id","type":0,"val":"media","end":""},{"old":"/api/v1/media/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['media_assets.destroy']['types'],
  },
  'media_assets.restore': {
    methods: ["POST"],
    pattern: '/api/v1/media/:id/restore',
    tokens: [{"old":"/api/v1/media/:id/restore","type":0,"val":"api","end":""},{"old":"/api/v1/media/:id/restore","type":0,"val":"v1","end":""},{"old":"/api/v1/media/:id/restore","type":0,"val":"media","end":""},{"old":"/api/v1/media/:id/restore","type":1,"val":"id","end":""},{"old":"/api/v1/media/:id/restore","type":0,"val":"restore","end":""}],
    types: placeholder as Registry['media_assets.restore']['types'],
  },
  'media_assets.purge': {
    methods: ["POST"],
    pattern: '/api/v1/media/:id/purge',
    tokens: [{"old":"/api/v1/media/:id/purge","type":0,"val":"api","end":""},{"old":"/api/v1/media/:id/purge","type":0,"val":"v1","end":""},{"old":"/api/v1/media/:id/purge","type":0,"val":"media","end":""},{"old":"/api/v1/media/:id/purge","type":1,"val":"id","end":""},{"old":"/api/v1/media/:id/purge","type":0,"val":"purge","end":""}],
    types: placeholder as Registry['media_assets.purge']['types'],
  },
  'knowledge_documents.index': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/ai/knowledge-documents',
    tokens: [{"old":"/api/v1/ai/knowledge-documents","type":0,"val":"api","end":""},{"old":"/api/v1/ai/knowledge-documents","type":0,"val":"v1","end":""},{"old":"/api/v1/ai/knowledge-documents","type":0,"val":"ai","end":""},{"old":"/api/v1/ai/knowledge-documents","type":0,"val":"knowledge-documents","end":""}],
    types: placeholder as Registry['knowledge_documents.index']['types'],
  },
  'knowledge_documents.store': {
    methods: ["POST"],
    pattern: '/api/v1/ai/knowledge-documents',
    tokens: [{"old":"/api/v1/ai/knowledge-documents","type":0,"val":"api","end":""},{"old":"/api/v1/ai/knowledge-documents","type":0,"val":"v1","end":""},{"old":"/api/v1/ai/knowledge-documents","type":0,"val":"ai","end":""},{"old":"/api/v1/ai/knowledge-documents","type":0,"val":"knowledge-documents","end":""}],
    types: placeholder as Registry['knowledge_documents.store']['types'],
  },
  'knowledge_documents.show': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/ai/knowledge-documents/:id',
    tokens: [{"old":"/api/v1/ai/knowledge-documents/:id","type":0,"val":"api","end":""},{"old":"/api/v1/ai/knowledge-documents/:id","type":0,"val":"v1","end":""},{"old":"/api/v1/ai/knowledge-documents/:id","type":0,"val":"ai","end":""},{"old":"/api/v1/ai/knowledge-documents/:id","type":0,"val":"knowledge-documents","end":""},{"old":"/api/v1/ai/knowledge-documents/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['knowledge_documents.show']['types'],
  },
  'knowledge_documents.complete_upload': {
    methods: ["POST"],
    pattern: '/api/v1/ai/knowledge-documents/:id/complete-upload',
    tokens: [{"old":"/api/v1/ai/knowledge-documents/:id/complete-upload","type":0,"val":"api","end":""},{"old":"/api/v1/ai/knowledge-documents/:id/complete-upload","type":0,"val":"v1","end":""},{"old":"/api/v1/ai/knowledge-documents/:id/complete-upload","type":0,"val":"ai","end":""},{"old":"/api/v1/ai/knowledge-documents/:id/complete-upload","type":0,"val":"knowledge-documents","end":""},{"old":"/api/v1/ai/knowledge-documents/:id/complete-upload","type":1,"val":"id","end":""},{"old":"/api/v1/ai/knowledge-documents/:id/complete-upload","type":0,"val":"complete-upload","end":""}],
    types: placeholder as Registry['knowledge_documents.complete_upload']['types'],
  },
  'knowledge_documents.destroy': {
    methods: ["DELETE"],
    pattern: '/api/v1/ai/knowledge-documents/:id',
    tokens: [{"old":"/api/v1/ai/knowledge-documents/:id","type":0,"val":"api","end":""},{"old":"/api/v1/ai/knowledge-documents/:id","type":0,"val":"v1","end":""},{"old":"/api/v1/ai/knowledge-documents/:id","type":0,"val":"ai","end":""},{"old":"/api/v1/ai/knowledge-documents/:id","type":0,"val":"knowledge-documents","end":""},{"old":"/api/v1/ai/knowledge-documents/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['knowledge_documents.destroy']['types'],
  },
  'knowledge_documents.restore': {
    methods: ["POST"],
    pattern: '/api/v1/ai/knowledge-documents/:id/restore',
    tokens: [{"old":"/api/v1/ai/knowledge-documents/:id/restore","type":0,"val":"api","end":""},{"old":"/api/v1/ai/knowledge-documents/:id/restore","type":0,"val":"v1","end":""},{"old":"/api/v1/ai/knowledge-documents/:id/restore","type":0,"val":"ai","end":""},{"old":"/api/v1/ai/knowledge-documents/:id/restore","type":0,"val":"knowledge-documents","end":""},{"old":"/api/v1/ai/knowledge-documents/:id/restore","type":1,"val":"id","end":""},{"old":"/api/v1/ai/knowledge-documents/:id/restore","type":0,"val":"restore","end":""}],
    types: placeholder as Registry['knowledge_documents.restore']['types'],
  },
  'knowledge_documents.purge': {
    methods: ["POST"],
    pattern: '/api/v1/ai/knowledge-documents/:id/purge',
    tokens: [{"old":"/api/v1/ai/knowledge-documents/:id/purge","type":0,"val":"api","end":""},{"old":"/api/v1/ai/knowledge-documents/:id/purge","type":0,"val":"v1","end":""},{"old":"/api/v1/ai/knowledge-documents/:id/purge","type":0,"val":"ai","end":""},{"old":"/api/v1/ai/knowledge-documents/:id/purge","type":0,"val":"knowledge-documents","end":""},{"old":"/api/v1/ai/knowledge-documents/:id/purge","type":1,"val":"id","end":""},{"old":"/api/v1/ai/knowledge-documents/:id/purge","type":0,"val":"purge","end":""}],
    types: placeholder as Registry['knowledge_documents.purge']['types'],
  },
  'flows.index': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/flows',
    tokens: [{"old":"/api/v1/flows","type":0,"val":"api","end":""},{"old":"/api/v1/flows","type":0,"val":"v1","end":""},{"old":"/api/v1/flows","type":0,"val":"flows","end":""}],
    types: placeholder as Registry['flows.index']['types'],
  },
  'flows.store': {
    methods: ["POST"],
    pattern: '/api/v1/flows',
    tokens: [{"old":"/api/v1/flows","type":0,"val":"api","end":""},{"old":"/api/v1/flows","type":0,"val":"v1","end":""},{"old":"/api/v1/flows","type":0,"val":"flows","end":""}],
    types: placeholder as Registry['flows.store']['types'],
  },
  'flows.show': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/flows/:id',
    tokens: [{"old":"/api/v1/flows/:id","type":0,"val":"api","end":""},{"old":"/api/v1/flows/:id","type":0,"val":"v1","end":""},{"old":"/api/v1/flows/:id","type":0,"val":"flows","end":""},{"old":"/api/v1/flows/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['flows.show']['types'],
  },
  'flows.update': {
    methods: ["PATCH"],
    pattern: '/api/v1/flows/:id',
    tokens: [{"old":"/api/v1/flows/:id","type":0,"val":"api","end":""},{"old":"/api/v1/flows/:id","type":0,"val":"v1","end":""},{"old":"/api/v1/flows/:id","type":0,"val":"flows","end":""},{"old":"/api/v1/flows/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['flows.update']['types'],
  },
  'flows.validate': {
    methods: ["POST"],
    pattern: '/api/v1/flows/:id/validate',
    tokens: [{"old":"/api/v1/flows/:id/validate","type":0,"val":"api","end":""},{"old":"/api/v1/flows/:id/validate","type":0,"val":"v1","end":""},{"old":"/api/v1/flows/:id/validate","type":0,"val":"flows","end":""},{"old":"/api/v1/flows/:id/validate","type":1,"val":"id","end":""},{"old":"/api/v1/flows/:id/validate","type":0,"val":"validate","end":""}],
    types: placeholder as Registry['flows.validate']['types'],
  },
  'flows.publish': {
    methods: ["POST"],
    pattern: '/api/v1/flows/:id/publish',
    tokens: [{"old":"/api/v1/flows/:id/publish","type":0,"val":"api","end":""},{"old":"/api/v1/flows/:id/publish","type":0,"val":"v1","end":""},{"old":"/api/v1/flows/:id/publish","type":0,"val":"flows","end":""},{"old":"/api/v1/flows/:id/publish","type":1,"val":"id","end":""},{"old":"/api/v1/flows/:id/publish","type":0,"val":"publish","end":""}],
    types: placeholder as Registry['flows.publish']['types'],
  },
  'flows.destroy': {
    methods: ["DELETE"],
    pattern: '/api/v1/flows/:id',
    tokens: [{"old":"/api/v1/flows/:id","type":0,"val":"api","end":""},{"old":"/api/v1/flows/:id","type":0,"val":"v1","end":""},{"old":"/api/v1/flows/:id","type":0,"val":"flows","end":""},{"old":"/api/v1/flows/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['flows.destroy']['types'],
  },
  'campaigns.index': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/campaigns',
    tokens: [{"old":"/api/v1/campaigns","type":0,"val":"api","end":""},{"old":"/api/v1/campaigns","type":0,"val":"v1","end":""},{"old":"/api/v1/campaigns","type":0,"val":"campaigns","end":""}],
    types: placeholder as Registry['campaigns.index']['types'],
  },
  'campaigns.preview': {
    methods: ["POST"],
    pattern: '/api/v1/campaigns/:id/preview',
    tokens: [{"old":"/api/v1/campaigns/:id/preview","type":0,"val":"api","end":""},{"old":"/api/v1/campaigns/:id/preview","type":0,"val":"v1","end":""},{"old":"/api/v1/campaigns/:id/preview","type":0,"val":"campaigns","end":""},{"old":"/api/v1/campaigns/:id/preview","type":1,"val":"id","end":""},{"old":"/api/v1/campaigns/:id/preview","type":0,"val":"preview","end":""}],
    types: placeholder as Registry['campaigns.preview']['types'],
  },
  'campaigns.send': {
    methods: ["POST"],
    pattern: '/api/v1/campaigns/:id/send',
    tokens: [{"old":"/api/v1/campaigns/:id/send","type":0,"val":"api","end":""},{"old":"/api/v1/campaigns/:id/send","type":0,"val":"v1","end":""},{"old":"/api/v1/campaigns/:id/send","type":0,"val":"campaigns","end":""},{"old":"/api/v1/campaigns/:id/send","type":1,"val":"id","end":""},{"old":"/api/v1/campaigns/:id/send","type":0,"val":"send","end":""}],
    types: placeholder as Registry['campaigns.send']['types'],
  },
  'campaigns.schedule': {
    methods: ["POST"],
    pattern: '/api/v1/campaigns/:id/schedule',
    tokens: [{"old":"/api/v1/campaigns/:id/schedule","type":0,"val":"api","end":""},{"old":"/api/v1/campaigns/:id/schedule","type":0,"val":"v1","end":""},{"old":"/api/v1/campaigns/:id/schedule","type":0,"val":"campaigns","end":""},{"old":"/api/v1/campaigns/:id/schedule","type":1,"val":"id","end":""},{"old":"/api/v1/campaigns/:id/schedule","type":0,"val":"schedule","end":""}],
    types: placeholder as Registry['campaigns.schedule']['types'],
  },
  'campaigns.cancel': {
    methods: ["PATCH"],
    pattern: '/api/v1/campaigns/:id/cancel',
    tokens: [{"old":"/api/v1/campaigns/:id/cancel","type":0,"val":"api","end":""},{"old":"/api/v1/campaigns/:id/cancel","type":0,"val":"v1","end":""},{"old":"/api/v1/campaigns/:id/cancel","type":0,"val":"campaigns","end":""},{"old":"/api/v1/campaigns/:id/cancel","type":1,"val":"id","end":""},{"old":"/api/v1/campaigns/:id/cancel","type":0,"val":"cancel","end":""}],
    types: placeholder as Registry['campaigns.cancel']['types'],
  },
  'campaigns.duplicate': {
    methods: ["POST"],
    pattern: '/api/v1/campaigns/:id/duplicate',
    tokens: [{"old":"/api/v1/campaigns/:id/duplicate","type":0,"val":"api","end":""},{"old":"/api/v1/campaigns/:id/duplicate","type":0,"val":"v1","end":""},{"old":"/api/v1/campaigns/:id/duplicate","type":0,"val":"campaigns","end":""},{"old":"/api/v1/campaigns/:id/duplicate","type":1,"val":"id","end":""},{"old":"/api/v1/campaigns/:id/duplicate","type":0,"val":"duplicate","end":""}],
    types: placeholder as Registry['campaigns.duplicate']['types'],
  },
  'campaigns.show': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/campaigns/:id',
    tokens: [{"old":"/api/v1/campaigns/:id","type":0,"val":"api","end":""},{"old":"/api/v1/campaigns/:id","type":0,"val":"v1","end":""},{"old":"/api/v1/campaigns/:id","type":0,"val":"campaigns","end":""},{"old":"/api/v1/campaigns/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['campaigns.show']['types'],
  },
  'campaigns.store': {
    methods: ["POST"],
    pattern: '/api/v1/campaigns',
    tokens: [{"old":"/api/v1/campaigns","type":0,"val":"api","end":""},{"old":"/api/v1/campaigns","type":0,"val":"v1","end":""},{"old":"/api/v1/campaigns","type":0,"val":"campaigns","end":""}],
    types: placeholder as Registry['campaigns.store']['types'],
  },
  'campaigns.update': {
    methods: ["PATCH"],
    pattern: '/api/v1/campaigns/:id',
    tokens: [{"old":"/api/v1/campaigns/:id","type":0,"val":"api","end":""},{"old":"/api/v1/campaigns/:id","type":0,"val":"v1","end":""},{"old":"/api/v1/campaigns/:id","type":0,"val":"campaigns","end":""},{"old":"/api/v1/campaigns/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['campaigns.update']['types'],
  },
  'campaigns.replace_recipients': {
    methods: ["PUT"],
    pattern: '/api/v1/campaigns/:id/recipients',
    tokens: [{"old":"/api/v1/campaigns/:id/recipients","type":0,"val":"api","end":""},{"old":"/api/v1/campaigns/:id/recipients","type":0,"val":"v1","end":""},{"old":"/api/v1/campaigns/:id/recipients","type":0,"val":"campaigns","end":""},{"old":"/api/v1/campaigns/:id/recipients","type":1,"val":"id","end":""},{"old":"/api/v1/campaigns/:id/recipients","type":0,"val":"recipients","end":""}],
    types: placeholder as Registry['campaigns.replace_recipients']['types'],
  },
  'campaigns.soft_delete': {
    methods: ["DELETE"],
    pattern: '/api/v1/campaigns/:id',
    tokens: [{"old":"/api/v1/campaigns/:id","type":0,"val":"api","end":""},{"old":"/api/v1/campaigns/:id","type":0,"val":"v1","end":""},{"old":"/api/v1/campaigns/:id","type":0,"val":"campaigns","end":""},{"old":"/api/v1/campaigns/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['campaigns.soft_delete']['types'],
  },
  'inbox_events.stream': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/inbox/events',
    tokens: [{"old":"/api/v1/inbox/events","type":0,"val":"api","end":""},{"old":"/api/v1/inbox/events","type":0,"val":"v1","end":""},{"old":"/api/v1/inbox/events","type":0,"val":"inbox","end":""},{"old":"/api/v1/inbox/events","type":0,"val":"events","end":""}],
    types: placeholder as Registry['inbox_events.stream']['types'],
  },
  'conversations.index': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/inbox/conversations',
    tokens: [{"old":"/api/v1/inbox/conversations","type":0,"val":"api","end":""},{"old":"/api/v1/inbox/conversations","type":0,"val":"v1","end":""},{"old":"/api/v1/inbox/conversations","type":0,"val":"inbox","end":""},{"old":"/api/v1/inbox/conversations","type":0,"val":"conversations","end":""}],
    types: placeholder as Registry['conversations.index']['types'],
  },
  'conversations.store': {
    methods: ["POST"],
    pattern: '/api/v1/inbox/conversations',
    tokens: [{"old":"/api/v1/inbox/conversations","type":0,"val":"api","end":""},{"old":"/api/v1/inbox/conversations","type":0,"val":"v1","end":""},{"old":"/api/v1/inbox/conversations","type":0,"val":"inbox","end":""},{"old":"/api/v1/inbox/conversations","type":0,"val":"conversations","end":""}],
    types: placeholder as Registry['conversations.store']['types'],
  },
  'conversations.show': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/inbox/conversations/:id',
    tokens: [{"old":"/api/v1/inbox/conversations/:id","type":0,"val":"api","end":""},{"old":"/api/v1/inbox/conversations/:id","type":0,"val":"v1","end":""},{"old":"/api/v1/inbox/conversations/:id","type":0,"val":"inbox","end":""},{"old":"/api/v1/inbox/conversations/:id","type":0,"val":"conversations","end":""},{"old":"/api/v1/inbox/conversations/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['conversations.show']['types'],
  },
  'conversations.update': {
    methods: ["PATCH"],
    pattern: '/api/v1/inbox/conversations/:id',
    tokens: [{"old":"/api/v1/inbox/conversations/:id","type":0,"val":"api","end":""},{"old":"/api/v1/inbox/conversations/:id","type":0,"val":"v1","end":""},{"old":"/api/v1/inbox/conversations/:id","type":0,"val":"inbox","end":""},{"old":"/api/v1/inbox/conversations/:id","type":0,"val":"conversations","end":""},{"old":"/api/v1/inbox/conversations/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['conversations.update']['types'],
  },
  'conversations.assign': {
    methods: ["POST"],
    pattern: '/api/v1/inbox/conversations/:id/assign',
    tokens: [{"old":"/api/v1/inbox/conversations/:id/assign","type":0,"val":"api","end":""},{"old":"/api/v1/inbox/conversations/:id/assign","type":0,"val":"v1","end":""},{"old":"/api/v1/inbox/conversations/:id/assign","type":0,"val":"inbox","end":""},{"old":"/api/v1/inbox/conversations/:id/assign","type":0,"val":"conversations","end":""},{"old":"/api/v1/inbox/conversations/:id/assign","type":1,"val":"id","end":""},{"old":"/api/v1/inbox/conversations/:id/assign","type":0,"val":"assign","end":""}],
    types: placeholder as Registry['conversations.assign']['types'],
  },
  'conversations.close': {
    methods: ["POST"],
    pattern: '/api/v1/inbox/conversations/:id/close',
    tokens: [{"old":"/api/v1/inbox/conversations/:id/close","type":0,"val":"api","end":""},{"old":"/api/v1/inbox/conversations/:id/close","type":0,"val":"v1","end":""},{"old":"/api/v1/inbox/conversations/:id/close","type":0,"val":"inbox","end":""},{"old":"/api/v1/inbox/conversations/:id/close","type":0,"val":"conversations","end":""},{"old":"/api/v1/inbox/conversations/:id/close","type":1,"val":"id","end":""},{"old":"/api/v1/inbox/conversations/:id/close","type":0,"val":"close","end":""}],
    types: placeholder as Registry['conversations.close']['types'],
  },
  'conversations.reopen': {
    methods: ["POST"],
    pattern: '/api/v1/inbox/conversations/:id/reopen',
    tokens: [{"old":"/api/v1/inbox/conversations/:id/reopen","type":0,"val":"api","end":""},{"old":"/api/v1/inbox/conversations/:id/reopen","type":0,"val":"v1","end":""},{"old":"/api/v1/inbox/conversations/:id/reopen","type":0,"val":"inbox","end":""},{"old":"/api/v1/inbox/conversations/:id/reopen","type":0,"val":"conversations","end":""},{"old":"/api/v1/inbox/conversations/:id/reopen","type":1,"val":"id","end":""},{"old":"/api/v1/inbox/conversations/:id/reopen","type":0,"val":"reopen","end":""}],
    types: placeholder as Registry['conversations.reopen']['types'],
  },
  'messages.index': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/inbox/conversations/:id/messages',
    tokens: [{"old":"/api/v1/inbox/conversations/:id/messages","type":0,"val":"api","end":""},{"old":"/api/v1/inbox/conversations/:id/messages","type":0,"val":"v1","end":""},{"old":"/api/v1/inbox/conversations/:id/messages","type":0,"val":"inbox","end":""},{"old":"/api/v1/inbox/conversations/:id/messages","type":0,"val":"conversations","end":""},{"old":"/api/v1/inbox/conversations/:id/messages","type":1,"val":"id","end":""},{"old":"/api/v1/inbox/conversations/:id/messages","type":0,"val":"messages","end":""}],
    types: placeholder as Registry['messages.index']['types'],
  },
  'messages.store': {
    methods: ["POST"],
    pattern: '/api/v1/inbox/conversations/:id/messages',
    tokens: [{"old":"/api/v1/inbox/conversations/:id/messages","type":0,"val":"api","end":""},{"old":"/api/v1/inbox/conversations/:id/messages","type":0,"val":"v1","end":""},{"old":"/api/v1/inbox/conversations/:id/messages","type":0,"val":"inbox","end":""},{"old":"/api/v1/inbox/conversations/:id/messages","type":0,"val":"conversations","end":""},{"old":"/api/v1/inbox/conversations/:id/messages","type":1,"val":"id","end":""},{"old":"/api/v1/inbox/conversations/:id/messages","type":0,"val":"messages","end":""}],
    types: placeholder as Registry['messages.store']['types'],
  },
  'conversation_ai.takeover': {
    methods: ["POST"],
    pattern: '/api/v1/inbox/conversations/:id/ai/takeover',
    tokens: [{"old":"/api/v1/inbox/conversations/:id/ai/takeover","type":0,"val":"api","end":""},{"old":"/api/v1/inbox/conversations/:id/ai/takeover","type":0,"val":"v1","end":""},{"old":"/api/v1/inbox/conversations/:id/ai/takeover","type":0,"val":"inbox","end":""},{"old":"/api/v1/inbox/conversations/:id/ai/takeover","type":0,"val":"conversations","end":""},{"old":"/api/v1/inbox/conversations/:id/ai/takeover","type":1,"val":"id","end":""},{"old":"/api/v1/inbox/conversations/:id/ai/takeover","type":0,"val":"ai","end":""},{"old":"/api/v1/inbox/conversations/:id/ai/takeover","type":0,"val":"takeover","end":""}],
    types: placeholder as Registry['conversation_ai.takeover']['types'],
  },
  'conversation_ai.resume': {
    methods: ["POST"],
    pattern: '/api/v1/inbox/conversations/:id/ai/resume',
    tokens: [{"old":"/api/v1/inbox/conversations/:id/ai/resume","type":0,"val":"api","end":""},{"old":"/api/v1/inbox/conversations/:id/ai/resume","type":0,"val":"v1","end":""},{"old":"/api/v1/inbox/conversations/:id/ai/resume","type":0,"val":"inbox","end":""},{"old":"/api/v1/inbox/conversations/:id/ai/resume","type":0,"val":"conversations","end":""},{"old":"/api/v1/inbox/conversations/:id/ai/resume","type":1,"val":"id","end":""},{"old":"/api/v1/inbox/conversations/:id/ai/resume","type":0,"val":"ai","end":""},{"old":"/api/v1/inbox/conversations/:id/ai/resume","type":0,"val":"resume","end":""}],
    types: placeholder as Registry['conversation_ai.resume']['types'],
  },
  'conversation_notes.index': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/inbox/conversations/:id/notes',
    tokens: [{"old":"/api/v1/inbox/conversations/:id/notes","type":0,"val":"api","end":""},{"old":"/api/v1/inbox/conversations/:id/notes","type":0,"val":"v1","end":""},{"old":"/api/v1/inbox/conversations/:id/notes","type":0,"val":"inbox","end":""},{"old":"/api/v1/inbox/conversations/:id/notes","type":0,"val":"conversations","end":""},{"old":"/api/v1/inbox/conversations/:id/notes","type":1,"val":"id","end":""},{"old":"/api/v1/inbox/conversations/:id/notes","type":0,"val":"notes","end":""}],
    types: placeholder as Registry['conversation_notes.index']['types'],
  },
  'conversation_notes.store': {
    methods: ["POST"],
    pattern: '/api/v1/inbox/conversations/:id/notes',
    tokens: [{"old":"/api/v1/inbox/conversations/:id/notes","type":0,"val":"api","end":""},{"old":"/api/v1/inbox/conversations/:id/notes","type":0,"val":"v1","end":""},{"old":"/api/v1/inbox/conversations/:id/notes","type":0,"val":"inbox","end":""},{"old":"/api/v1/inbox/conversations/:id/notes","type":0,"val":"conversations","end":""},{"old":"/api/v1/inbox/conversations/:id/notes","type":1,"val":"id","end":""},{"old":"/api/v1/inbox/conversations/:id/notes","type":0,"val":"notes","end":""}],
    types: placeholder as Registry['conversation_notes.store']['types'],
  },
  'billing.list_plans': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/billing/plans',
    tokens: [{"old":"/api/v1/billing/plans","type":0,"val":"api","end":""},{"old":"/api/v1/billing/plans","type":0,"val":"v1","end":""},{"old":"/api/v1/billing/plans","type":0,"val":"billing","end":""},{"old":"/api/v1/billing/plans","type":0,"val":"plans","end":""}],
    types: placeholder as Registry['billing.list_plans']['types'],
  },
  'billing.show_subscription': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/billing/subscription',
    tokens: [{"old":"/api/v1/billing/subscription","type":0,"val":"api","end":""},{"old":"/api/v1/billing/subscription","type":0,"val":"v1","end":""},{"old":"/api/v1/billing/subscription","type":0,"val":"billing","end":""},{"old":"/api/v1/billing/subscription","type":0,"val":"subscription","end":""}],
    types: placeholder as Registry['billing.show_subscription']['types'],
  },
  'billing.show_entitlements': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/billing/entitlements',
    tokens: [{"old":"/api/v1/billing/entitlements","type":0,"val":"api","end":""},{"old":"/api/v1/billing/entitlements","type":0,"val":"v1","end":""},{"old":"/api/v1/billing/entitlements","type":0,"val":"billing","end":""},{"old":"/api/v1/billing/entitlements","type":0,"val":"entitlements","end":""}],
    types: placeholder as Registry['billing.show_entitlements']['types'],
  },
  'billing.checkout': {
    methods: ["POST"],
    pattern: '/api/v1/billing/checkout',
    tokens: [{"old":"/api/v1/billing/checkout","type":0,"val":"api","end":""},{"old":"/api/v1/billing/checkout","type":0,"val":"v1","end":""},{"old":"/api/v1/billing/checkout","type":0,"val":"billing","end":""},{"old":"/api/v1/billing/checkout","type":0,"val":"checkout","end":""}],
    types: placeholder as Registry['billing.checkout']['types'],
  },
  'billing.verify': {
    methods: ["POST"],
    pattern: '/api/v1/billing/verify',
    tokens: [{"old":"/api/v1/billing/verify","type":0,"val":"api","end":""},{"old":"/api/v1/billing/verify","type":0,"val":"v1","end":""},{"old":"/api/v1/billing/verify","type":0,"val":"billing","end":""},{"old":"/api/v1/billing/verify","type":0,"val":"verify","end":""}],
    types: placeholder as Registry['billing.verify']['types'],
  },
  'notifications.index': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/notifications',
    tokens: [{"old":"/api/v1/notifications","type":0,"val":"api","end":""},{"old":"/api/v1/notifications","type":0,"val":"v1","end":""},{"old":"/api/v1/notifications","type":0,"val":"notifications","end":""}],
    types: placeholder as Registry['notifications.index']['types'],
  },
  'notifications.mark_all_as_read': {
    methods: ["PATCH"],
    pattern: '/api/v1/notifications/read-all',
    tokens: [{"old":"/api/v1/notifications/read-all","type":0,"val":"api","end":""},{"old":"/api/v1/notifications/read-all","type":0,"val":"v1","end":""},{"old":"/api/v1/notifications/read-all","type":0,"val":"notifications","end":""},{"old":"/api/v1/notifications/read-all","type":0,"val":"read-all","end":""}],
    types: placeholder as Registry['notifications.mark_all_as_read']['types'],
  },
  'notifications.mark_as_read': {
    methods: ["PATCH"],
    pattern: '/api/v1/notifications/:id/read',
    tokens: [{"old":"/api/v1/notifications/:id/read","type":0,"val":"api","end":""},{"old":"/api/v1/notifications/:id/read","type":0,"val":"v1","end":""},{"old":"/api/v1/notifications/:id/read","type":0,"val":"notifications","end":""},{"old":"/api/v1/notifications/:id/read","type":1,"val":"id","end":""},{"old":"/api/v1/notifications/:id/read","type":0,"val":"read","end":""}],
    types: placeholder as Registry['notifications.mark_as_read']['types'],
  },
} as const satisfies Record<string, AdonisEndpoint>

export { routes }

export const registry = {
  routes,
  $tree: {} as ApiDefinition,
}

declare module '@tuyau/core/types' {
  export interface UserRegistry {
    routes: typeof routes
    $tree: ApiDefinition
  }
}
