import type { Metadata } from 'next'
import { notoSans, nunitoSans, inter } from './fonts'
import './globals.css'
import { cn } from '@/lib/utils'

export const metadata: Metadata = {
  title: 'App',
  description: 'Generated by rxzn',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return children;
}
